### ISSUE TITLE
String of fcm_sender_id unnecessarily needs to be in strings.xml

### ISSUE THREAD

**Issue by peterbetos** [Pushwoosh/pushwoosh-android-sdk#102]
Can the library be updated to also handle the fcm_sender_id value as a resConfig inside build.gradle? Thanks.

**Comment by wfhm** [comment]
Hi,

Could you please elaborate on this issue?

If you want to specify fcm_sender_id inside your build.gradle, you can do it with manifestPlaceholders, just make sure to add an "A" prefix to it, so it could be recognized as a string:

```
defaultConfig {
applicationId "com.pushwoosh.testingapp"
minSdkVersion 14
targetSdkVersion global_targetVersion
versionCode 1
versionName "1.0"
manifestPlaceholders = [pw_appid : "12345-1A2B3",
fcm_project_number: "A123456789012"]
}
```

In manifest it will look like below:

```
<meta-data
android:name="com.pushwoosh.appid"
android:value="${pw_appid}" />
<meta-data
android:name="com.pushwoosh.senderid"
android:value="${fcm_project_number}" />
```

**Comment by peterbetos** [comment]
Thanks for this, we'll test this.

**Comment by peterbetos** [comment]
We can close this. It's working as a manifest placeholder value. Thanks.
