### ISSUE TITLE
How to keep old users connected after migrating to FCM

### ISSUE THREAD

**Issue by AhmedDroid** [Pushwoosh/pushwoosh-android-sdk#105]
Dears,

If I initiated the migration process from GCM to FCM using pushwoosh SDK, how can I ensure that old users with builds communicating with the GCM project stay notified? would they be left in the dark after putting my new sender id from FCM?

**Comment by wfhm** [comment]
Hi,

According to Google docs:

> We will continue to support the current version of GCM Android and iOS SDKs because we know a lot of developers are using GCM SDKs today to handle notifications, and client app upgrade takes time.

> But all new client-side features will be added to FCM SDKs only moving forward. You are strongly encouraged to upgrade to FCM SDKs.

Your older builds will still be able to receive push notifications sent via FCM, as GCM is now only an integrated part of FCM. 

Please note that your Sender ID *should not change after migrating* - it should be the same as your Google project number. If it changes after migration, do not use it and please let us know about it.
