### ISSUE TITLE
Don't work notifications in Android Oreo(api 27+)

### ISSUE THREAD

**Issue by pashko00710** [Pushwoosh/pushwoosh-android-sdk#106]
**Good afternoon!**

The problem is that the intent is in the receiver, but the bundle is zero (when we write `PushManagerImpl.preHandlePush (context, intent)`). 

What could be the problem? 

Since on api less than 27 everything works well! Version of pushwoosh 4.12.0

Thanks in advance and do not throw tomatoes, if this is not a bug, but my mistake.

**Comment by wfhm** [comment]
Hi,

Android Oreo support was introduced with 5.0.3 version, therefore we strongly recommend updating your SDK to the latest version.

Please note that SDK was refactored, most classes were deprecated and some became obsolete. Please take a look on our migration guide:

https://docs.pushwoosh.com/docs/pushwoosh-android-sdk-50-migration-guide
https://docs.pushwoosh.com/docs/fcm-configuration

**Comment by pashko00710** [comment]
Thanks for the quick response! 
We will pass!
