### ISSUE TITLE
Deploy releases to a public maven repository

### ISSUE THREAD

**Issue by SebastianEngel** [Pushwoosh/pushwoosh-android-sdk#11]
Please deploy the versioned releases (see #10) to a public maven repository like "jcenter" or "maven central". This way the library dependency can simply be defined in the project's configuration dependency block (e.g. build.gradle). The build system will handle everything else.

**Comment by shaders** [comment]
Done:
http://search.maven.org/#search%7Cga%7C1%7Cpushwoosh
