### ISSUE TITLE
How to disable [PushwooshModule] in some Flavors

### ISSUE THREAD

**Issue by francescogatto** [Pushwoosh/pushwoosh-android-sdk#110]
Hi, i'm using PushWoosh in a Flavor. In an another one i don't call register/unregister device and the manifest doesn't have any reference to PushWoosh. I'm wondering why the Library, when start the application builded with this flavor, init anyway the module and call the url of the other flavor to register the device. Thx

**Comment by wfhm** [comment]
@francescogatto 

This is quite strange. A device should never register for pushes if you do not call `registerForPushNotifications()` method. It will still init the SDK and send other requests, such as /applicationOpen, /getInApps, /registerUser and several others, however without specifically calling device registration, it should never register for pushes. Could it be you mixed up /registerUser request with a /registerDevice? 

As for initing the SDK, it is a default behavior, and there is no control over it. Once Pushwoosh SDK is added, it will try to initialize on application start. However you can disable sending all SDK requests by not setting App ID for your second flavor.

Could it work for you? Also, may I ask you to describe your use-case in a bit more details so I could assist you better?

**Comment by francescogatto** [comment]
> Could it work for you? Also, may I ask you to describe your use-case in a bit more details so I could assist you better?

It worked, I wrote empty AppID for the other flavor
Thanks
