### ISSUE TITLE
There is no method setUserId in SDK

### ISSUE THREAD

**Issue by agent10** [Pushwoosh/pushwoosh-android-sdk#111]
There is description here https://www.pushwoosh.com/docs/user-id-push#section-collecting-user-ids
but no method in SDK.
iOS SDK has this method.

**Comment by wfhm** [comment]
Hi,

There is such a method in `PushwooshInApp` class:

https://rawgit.com/Pushwoosh/pushwoosh-android-sdk/master/Documentation/com/pushwoosh/inapp/PushwooshInApp.html#setUserId-java.lang.String-

Please let me know if it does not work for you.

**Comment by vixez** [comment]
Hello,

I had this issue as well. 
You are supposed to use the `PushwooshInApp` class even for regular push notifications.

`import com.pushwoosh.inapp.PushwooshInApp;`
`PushwooshInApp.getInstance().setUserId("your-user-id")`

When you register for push notifications you will see the userId is sent in the payload.
