### ISSUE TITLE
Samsung S9 unable to schedule local notification

### ISSUE THREAD

**Issue by mihailogazda** [Pushwoosh/pushwoosh-android-sdk#113]
Hey,

So seems on Android 8.0 and Galaxy S9 local notifications not working, with exception : 
"**No Channel found for pkg**"

We tried updating to latest 5.8.4 version...

`08-07 17:01:05.277: I/Prime31-AlarmManagerReceiver(30202): got notification while we are NOT running so posting now
08-07 17:01:05.293: I/Prime31-AlarmManagerReceiver(30202): attempting to find smallIcon resource ID dynamically...
08-07 17:01:05.293: I/Prime31-AlarmManagerReceiver(30202): smallIcon resource ID: 2131099813
08-07 17:01:05.293: I/Prime31-AlarmManagerReceiver(30202): using notification defaults value: 3
08-07 17:01:05.294: I/Prime31-AlarmManagerReceiver(30202): notification Uri: content://settings/system/notification_sound
08-07 17:01:05.302: D/ApplicationPolicy(4823): isStatusBarNotificationAllowedAsUser: packageName = com.ubisoft.hungrysharkworld,userId = 0
08-07 17:01:05.302: D/API test(4823): getContainerInfo: value is 
08-07 17:01:05.303: E/NotificationService(4823): No Channel found for pkg=com.ubisoft.hungrysharkworld, channelId=null, id=30634845, tag=null, opPkg=com.ubisoft.hungrysharkworld, callingUid=10431, userId=0, incomingUserId=0, notificationUid=10431, notification=Notification(channel=null pri=0 contentView=null vibrate=default sound=default tick defaults=0x3 flags=0x10 color=0x00000000 number=0 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
08-07 17:01:05.304: I/Prime31-AlarmManagerReceiver(30202): notification posted with requestCode/notification Id: 30634845`

**Comment by tobeee** [comment]
Did you manage to find a solution to this?
