### ISSUE TITLE
Crash on RuntimeException / ClassCastException

### ISSUE THREAD

**Issue by mihailogazda** [Pushwoosh/pushwoosh-android-sdk#114]
Hey Pushwoosh, we see lots of crashes on Android - live environment (even though we haven't seen in the office), seem to be comming from Pushwoosh and is happening quite a lot... 

![image](https://user-images.githubusercontent.com/2773099/46413332-95baf400-c718-11e8-9c47-30bf3a1001f7.png)

Doesn't seem to be any specific OS / device, but spread out across...

![image](https://user-images.githubusercontent.com/2773099/46413371-ac614b00-c718-11e8-8d2b-13a5f63623c9.png)

Did you saw this before? Is it maybe fixed in some of the releases? 

We are using Unity 2017.1.2p4 with PW Android: 5.7.3 / iOS: 5.7.3.

**Comment by wfhm** [comment]
Hi @mihailogazda ,

We have recently received the same report, already investigating it.

**Comment by wfhm** [comment]
@mihailogazda Were you able to reproduce the issue locally, or it is only shown in GA reports? By any chance is it possible to provide us with a reproducer apk or project?

**Comment by mihailogazda** [comment]
@wfhm Sadly we only see it at GA, couldn't get it in house... The app in question is: https://play.google.com/store/apps/details?id=com.ubisoft.hungrysharkworld&hl=en_GB

**Comment by wfhm** [comment]
@mihailogazda Just a quick update here.

We were unable to reproduce the issue so far, so it is quite difficult to find where it comes from. We are going to add a temporary workaround to prevent crashes with the next release until there is more information to work with.

**Comment by mihailogazda** [comment]
@wfhm  Thanks, we'll update to that once you do, and let you know if it helped or not 👍

**Comment by wfhm** [comment]
@mihailogazda I'm sorry for not updating you timely! The fix is out and the issue is seemingly solved, as we do not see it anymore in our crash reporting. Please try updating to the latest version and let us know about the results.
