### ISSUE TITLE
Stay Tuned Pop-Up Showing

### ISSUE THREAD

**Issue by ananth10** [Pushwoosh/pushwoosh-android-sdk#115]
Hello Team ,

 Its was working good in v5.5.2 . but I have updated to v5.9.0 now I am seeing pop-up when i open app for first time. how to remove/hide this popup ?please check attached screenshot below.

and also seeing "stopped by app" toast message sometimes.

![screenshot_20181016-200715](https://user-images.githubusercontent.com/13381242/47024628-b86cf400-d17f-11e8-998e-c7e124a7bb1d.png)

**Comment by wfhm** [comment]
Hi,

You can disable this pop up in your Control Panel - just go to In-Apps section, find a corresponding one and disable it. Please note that by default it should be disabled, so please check with your team if it was turned on occasionally?

**Comment by ananth10** [comment]
@wfhm Okay . I will check it. Thanks

**Comment by ananth10** [comment]
@wfhm can you tell me which control panel ? you mean pushwoosh dashboard in website?

**Comment by wfhm** [comment]
@ananth10 Yes, exactly.

This feature was added after 5.5.2 release, this is why do not see it with earlier versions.

**Comment by ananth10** [comment]
@wfhm . can you tell me which control panel ? you mean pushwoosh dashboard in website?

**Comment by wfhm** [comment]
@ananth10 Yes, I meant the [Pushwoosh dashboard](go.pushwoosh.com). To disable this In-App you should choose your application and open In-Apps tab. There you will find the "Increase Push Opt-In rate" In-App - you can either completely remove it or simply disable it by specifying End date in Edit tab.
