### ISSUE TITLE
Potential Security Vulnerability - Zipperdown

### ISSUE THREAD

**Issue by rossmartin** [Pushwoosh/pushwoosh-android-sdk#121]
A company that I consult for uses Data Theorem to scan for security vulnerabilities.  They are stating that one of our apps might be vulnerable to Zipperdown because of the Pushwoosh SDK -
 
> The following Java classes within the App unzip archives in an insecure manner and might be vulnerable to the ZipperDown vulnerability:
> 
> • com.pushwoosh.internal.utils.c

The app in question is using version 4.6.3 of the SDK here.  I can't tell if or how the compiled SDK uses `java.util.zip`.  Can anyone confirm if and how it is used?

**Comment by wfhm** [comment]
Hi @rossmartin,

Thank you for reporting this one. Checking it.

**Comment by JenyaKirmizaTripTop** [comment]
same here +

**Comment by JenyaKirmiza** [comment]
same here, but other issue
high level vulnerability - com.pushwoosh.PushwooshSharedDataProvider it's exported content provider

**Comment by wfhm** [comment]
@rossmartin Confirmed, working on the fix now.

**Comment by m3toh** [comment]
Is the problem solved or not ?

**Comment by wfhm** [comment]
@m3toh 

Not yet, however right now we are working on it, so it will be fixed with the upcoming release.

**Comment by wfhm** [comment]
@m3toh fixed with the latest release.
