### ISSUE TITLE
Not show push notification in lock screen

### ISSUE THREAD

**Issue by alvaromarco** [Pushwoosh/pushwoosh-android-sdk#123]
Hi, I use pushwoosh 5.12.1 and I was migrate my app from 4.12.2 to 5.12.1 succesfully but I have a problem with notifications in lock screen.

When I launch push with my app in background or not executed,  the screen wake up but in lockscreen not show the notification. How can I configure the push to show in lock screen?
Info: compileSdkVersion 26 and targetSdkVersion 26
I show in logs that the push notification was received correctly.
I try to send "rich media" action but not work, initially use "open app" action.

**Comment by wfhm** [comment]
Hi @alvaromarco ,

To send a push visible on your lock screen, you should just add `"visibility":1` key-value pair to a notification object in your /createMessage API request.

**Comment by alvaromarco** [comment]
Hi, I think the problem is in another part of my code.
My app show a notification permanent

```
val mNotificationManager = context.getSystemService (NOTIFICATION_SERVICE) as NotificationManager
        mNotificationManager.notify (999, MY_PERMANENT_NOTIFICATION)
```
This notification has a unique channel and channel name, the problem it's when a new push notification received from my custom FirebaseMessagingService () catch the notification correctly in this method:
```
override fun onMessageReceived (remoteMessage: RemoteMessage?) {
}
```

And the problem is when call this method to show the notification:
```super.onMessageReceived (remoteMessage)```

The notification was not shown but sounds and wakeup locked screen.

Previously to migrate to FirebaseMessagingService (), I use GCMService () and the notification show correctly.

**I think it's something with the notification channel, I try to create in Application class another channel and send to push manually from web panel with specific channel as the PushWoosh doc says.**

Other test that confirm this theory, on:
```
override fun onMessageReceived (remoteMessage: RemoteMessage?) {
}
```

I create a new notification to show, this notification notify with other id like:
`` `
val mNotificationManager = context.getSystemService (Context.NOTIFICATION_SERVICE) as NotificationManager
            mNotificationManager.notify (2, notification)
`` `

And shows correctly two notifications in locked screen.

**Comment by alvaromarco** [comment]
> Hi @alvaromarco ,
> 
> To send a push visible on your lock screen, you should just add `"visibility":1` key-value pair to a notification object in your /createMessage API request.

This parameter `"visibility"`not appear in the documentation:
https://www.pushwoosh.com/v1.0/reference#getapplicationfile

**Comment by alvaromarco** [comment]
Any solution?

**Comment by wfhm** [comment]
@alvaromarco ,

Could you please describe the logics you use to create a notification on a lock screen in a bit more details? Also, could you please attach your custom FirebaseMessagingService code?

**Comment by alvaromarco** [comment]
In my Application class create a notification permanent
`class Application : MultiDexApplication() {

	override fun onCreate() {
        super.onCreate()
       
        createNotificationPermanent()

    }

    private fun createNotificationPermanent() {
    	if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channelId = "permanent_notification_id"
            val channelName = "permanent_notification"
            val channel = NotificationChannel(channelId, channelName, NotificationManager.IMPORTANCE_DEFAULT)

            channel.apply {
                vibrationPattern = longArrayOf(0.toLong())
                enableVibration(true)
                setSound(null, null)
                setShowBadge(false)
                lockscreenVisibility = Notification.VISIBILITY_PUBLIC
            }

            (context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager).createNotificationChannel(channel)

            return NotificationCompat.Builder(context, channelId)
                    .setSmallIcon(R.drawable.icon_call)
                    .setContent(view)
                    .setContentTitle(context.getString(R.string.app_name))
                    .setAutoCancel(false)
                    .setOngoing(true)
                    .setPriority(NotificationCompat.PRIORITY_MAX)
                    .build()
        } else {
            return NotificationCompat.Builder(context)
                    .setSmallIcon(R.drawable.icon_call)
                    .setContent(view)
                    .setContentTitle(context.getString(R.string.app_name))
                    .setAutoCancel(false)
                    .setOngoing(true)
                    .setPriority(NotificationCompat.PRIORITY_MAX).build()
        }

    }
}`

Then in my custom Service get the notification and show this:
`class PushNotificationService : FirebaseMessagingService() {

    override fun onCreate() {
        super.onCreate()
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            createNotificationChannel()
        }

    }

    @RequiresApi(api = Build.VERSION_CODES.O)
    private fun createNotificationChannel() {
        val channel = NotificationChannel("My_App", "App_Example", NotificationManager.IMPORTANCE_DEFAULT)
        val notificationManager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
        notificationManager.createNotificationChannel(channel)
    }

    override fun onMessageReceived(remoteMessage: RemoteMessage?) {
        super.onMessageReceived(remoteMessage)
        if (remoteMessage == null) {
            return
        }

        Log.d("My_App", "Message received")

        showNotification(remoteMessage)
    }

    private fun showNotification(remoteMessage: RemoteMessage) {
        super.onMessageReceived(remoteMessage)
    }

}`

I try to create a channel previously in Application class (move `createNotificationChannel()` to Application class) but not work. 
But, if I create a notification in `onMessageReceived()` works fine
`    private fun showNotification(remoteMessage: RemoteMessage) {

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channelId = "My_App"
            val channel = NotificationChannel(channelId, "Example App", NotificationManager.IMPORTANCE_DEFAULT)

            channel.apply {
                lockscreenVisibility = Notification.VISIBILITY_PUBLIC
                setShowBadge(false)
            }

            (context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager).createNotificationChannel(channel)

            val notification = NotificationCompat.Builder(context, channelId)
                    .setSmallIcon(R.drawable.pw_notification)
                    .setContentTitle("AAA")
                    .setContentText("Hello world")
                    .setPriority(NotificationCompat.PRIORITY_MAX)
                    .build()

            val mNotificationManager = context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
            mNotificationManager.notify(2, notification)
        } else {
            super.onMessageReceived(remoteMessage)
        }
    }
`

This service is define in AndroidManifest:
`xml <service
            android:name=".es.utils.PushNotificationService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>`

**The problem basic**: When notification received, not show on lockedscreen with only `super.onMessageReceived(remoteMessage)`

**Comment by wfhm** [comment]
@alvaromarco It looks like you do not use Pushwoosh SDK for generating and showing notifications at all. Therefore, a default channel is not added to your notifications, and you have to create it on your own. A channel is required for showing notifications on Android 8+ devices, so this is most likely why it is not working with only calling a super method.

**Comment by alvaromarco** [comment]
@wfhm I need the push notification payload to make some logic with this, not it's only show a notification.
The notification channel is set before in Application class and when I send a push notification from the pushwoosh panel, I add the param {"pw_channel": "PUSH NOTIFICATION CHANNEL NAME"} with my channel name correctly but not show the notification. Any idea?

**Comment by wfhm** [comment]
@alvaromarco We've investigated this behavior and it turns out you cannot set visibility for a channel in your code - `notificationChannel.lockscreenVisibility` is "only modifiable by the system and notification ranker" according to Google documentation. 

This method neither works from Activity nor from custom FirebaseMessagingService
Сделал пример с кодом чувака, метод notificationChannel.lockscreenVisibility не работает ни из activity, ни из сервиса, наследуемого от FirebaseMessagingService. The only way to control notification visibility on the lockscreen is to use `setVisibility` when creating a notification:

```
val notification = NotificationCompat.Builder(this, channelId)
 .setSmallIcon(R.mipmap.ic_launcher)
 .setContentTitle("AAA")
 .setContentText("Hello world")
 .setVisibility(Notification.VISIBILITY_PUBLIC) // this parameter is used to configure lock screen visibility
 .setPriority(NotificationCompat.PRIORITY_MAX)
 .build()
```

Please note that it will only work if global device settings are not restricting showing notifications on the lockscreen. Also, Pushwoosh SDK uses `Notification.VISIBILITY_PUBLIC` as a default value, so, if a device is allowed to show notification on a lockscreen, it will show it.
