### ISSUE TITLE
NullPointerException when badge number is set

### ISSUE THREAD

**Issue by Fishfield** [Pushwoosh/pushwoosh-android-sdk#128]
Since we did the update to `5.14.1` we are getting a `NullPointerException` when the badge number is set. We are not sending a null value to this method, so I am not sure why it is crashing. Maybe you can help us. This is one of our top 5 crashes in the current release. It is only happening on Android 9

`at com.pushwoosh.badge.PushwooshBadge.setBadgeNumber (PushwooshBadge.java:4)`

**Comment by wfhm** [comment]
@Fishfield I am sorry for such a delay with a response! This issue was skipped by our internal bug tracking system, hence a delay. Could you please let us know if the issue still persists?
