### ISSUE TITLE
Zip Path Traversal Vulnerability

### ISSUE THREAD

**Issue by reflexing** [Pushwoosh/pushwoosh-android-sdk#129]
Posting just in case you don't know, got this alert in Google Play console:

```
Security alert

Your app contains an unsafe unzipping pattern that may lead to a Path Traversal vulnerability. Please see this Google Help Center article to learn how to fix the issue.

Vulnerable locations:

com.pushwoosh.internal.utils.e.a
```

We are using Pushwoosh Unity plugin 5.9.0.

**Comment by wfhm** [comment]
Hi @reflexing,

Thank you for pointing this out! Yes, our Development team is already working on fixing this.

**Comment by Vall0n** [comment]
Here a link provided by google to fix it: https://support.google.com/faqs/answer/9294009

**Comment by wfhm** [comment]
@Vall0n

Thanks, we are already aware of this solution.

**Comment by wfhm** [comment]
@reflexing, @Vall0n

Fixed it in the latest version of Pushwoosh-Android SDK(5.14.3)

**Comment by Vall0n** [comment]
Thanks!

**Comment by VietPhanXuan** [comment]
Hi all, 
I'm updated in version 5.14.3 or newest version (5.18.0), but it happened this error:
![image](https://user-images.githubusercontent.com/33854600/62022512-e85d2380-b1f6-11e9-8191-c4a5ba086a4a.png)
