### ISSUE TITLE
Received: Bundle[{CMD=RST_FULL, from=google.com/iid, android.support.content.wakelockid=1}]

### ISSUE THREAD

**Issue by SebastianEngel** [Pushwoosh/pushwoosh-android-sdk#13]
We started to notice some push notification coming in that look like the following and happen only on (first?) app start:

```
Received: Bundle[{CMD=RST_FULL, from=google.com/iid, android.support.content.wakelockid=1}]
```

I found the following post on StackOverflow: http://stackoverflow.com/questions/30479424/weird-push-message-received-on-app-start

I assume that there is a change needed in the PushWoosh SDK due to this new GCM behavior. Could you please have a look at this?

**Comment by shaders** [comment]
Re-registration with the following command will be implemented in the upcoming minor release.
