### ISSUE TITLE
Pushwoosh.getInstance().getPushHistory() return 0

### ISSUE THREAD

**Issue by MathiewNguyen** [Pushwoosh/pushwoosh-android-sdk#130]
Dear All,

I'm using Pushwoosh version:
implementation 'com.pushwoosh:pushwoosh:5.9.3'

I want to get list notifications by using method:
`List<PushMessage> pushMessageHistory = Pushwoosh.getInstance().getPushHistory();`

But always return size = 0;
I use an enterprise account and tick on "save box" message on action tab when send push message from dashboard of Pushwoosh.

Appreciate if anyone can help with this error or any suggestion how to get list notification of Pushwoosh?

Thank you!

**Comment by wfhm** [comment]
Hi @MathiewNguyen,

Could you please elaborate on what exactly you want to achieve? Am I correct that you send pushes via Control Panel and save it to Inbox, and then you want to get all the messages a device has received? If so, you can use PushwooshInbox.loadMessages method to get all the messages saved to Inbox.

As for using getPushHistory() method, please check that PUSH_HISTORY_CAPACITY parameter is set to any value other than 0.

**Comment by MathiewNguyen** [comment]
Hi @wfhm ,
Thank you for quickly help.
Yes, I want to get a list of notification which have saved in the box of Pushwoosh.
Then I will show it under list on my application.
Currently, I'm using Pushwoosh version:
implementation 'com.pushwoosh:pushwoosh:5.9.3'
and using getPushHistory() to get list notification but It always return "0" in result.
Although, I have configed save to box notification on dashboard of pushwoosh.

As you suggested use PushwooshInbox.loadMessages, so what version Pushwoosh should I use to implement it?

Thanks.

**Comment by wfhm** [comment]
@MathiewNguyen,

The further investigation requires knowing your account name/ application code, so may I ask you to contact our support team using the form below and provide them with your application code, message IDs of the pushes you sent to be saved in inbox?

https://help.pushwoosh.com/hc/en-us/requests/new

Also please note that the latest Pushwoosh SDK release is 5.14.3, while 5.9.3 is dated November, 2018, so we strongly recommend updating it in your project.
