### ISSUE TITLE
Pushwoosh not using existing channel

### ISSUE THREAD

**Issue by Tregan** [Pushwoosh/pushwoosh-android-sdk#133]
Hello,

So our Flutter application uses the Pushwoosh Flutter plugin, but it also uses local notifications. I want both of them to use the same notification channel.

When starting the app, I create a notification channel in MainActivity.java making it always available. Sending a local notification to that channel works fine, but when I send a push notification (with Android root parameter {"pw_channel":"channel_name"} , according to https://www.pushwoosh.com/platform-docs/pushwoosh-sdk/android-push-notifications/notification-channels), a second channel is created. It does have the correct name, but it just shows 2 channels with the same name. I also tried {"pw_channel":"channel_id"}, but the result is the same.

I did look into creating my own factory, as described by https://www.pushwoosh.com/platform-docs/pushwoosh-sdk/android-push-notifications/customizing-android-sdk-5.0#customizing-push-notifications , but I don't want to lose the normal behaviour, and overriding addChannel isn't really feasible, since the NotificationFactory code is obfuscated.

Any ideas, or is this a bug? Thanks in advance!

Yours,
Bas

**Comment by wfhm** [comment]
@Tregan,

Would sharing the code responsible for generating Pushwoosh Channel ID help in your case?


    private static final String CHANNEL_ID_PREFIX = "pushwoosh_";

    static String channelId(String channelName) {
        if (!channelName.contains(" ") && channelName.startsWith(CHANNEL_ID_PREFIX)) {
           return channelName;
        }
        return CHANNEL_ID_PREFIX + channelName.trim().replaceAll("\\s+", "_").toLowerCase();
    }

You should just send a correct value with "pw_channel" parameter, assign generated Channel ID to your local notifications and use the same Channel name for both notification types.

The other option might be using getNotificationChannels() method to get all the channels of the app and use the one you need. However please keep in mind that a push channel is generated after the first push to this channel is received.

Would any of these options work for you?

**Comment by Tregan** [comment]
Perfect! On startup I now create a notification channel with pushwoosh_appname as its ID, which I also use for local notifications. then I just send {"pw_channel":"appname"} as notification argument, and that seems to work well. Thanks!

p.s. it looks like the notification channel is created even before you show a notification, if you create the channel using the NotificationManager.createNotificationChannel(channel) method. This way all settings can be set beforehand :)
