### ISSUE TITLE
[Question] AndroidX

### ISSUE THREAD

**Issue by sgrekov** [Pushwoosh/pushwoosh-android-sdk#134]
As far as I can see lates release of SDK is still dependent on com.android.support? When will the transition to AndroidX is planned?

**Comment by wfhm** [comment]
@sgrekov,

There is no ETA on the transition yet - most of the cross-platform frameworks (such as Cordova, Adobe Air etc.) still do not support AndroidX, so Pushwoosh plugins based on our native Android SDK for these frameworks have to stick with Android support libraries.

Meanwhile you can use Jetifier if you want to use Pushwoosh SDK work alongside with AndroidX libs.
