### ISSUE TITLE
Did not get device token from pushwoosh

### ISSUE THREAD

**Issue by ananth10** [Pushwoosh/pushwoosh-android-sdk#136]
Hi Team,

I have configured pushwoosh in our apps. recently app did not trigger any notification. then I looked in the code all I was getting "Stopped by in-app" error when I tried to register for push notification. please let me know how to resolve this bug.

Register **code**

`    Pushwoosh.getInstance().registerForPushNotifications(result -> {
            if (result.isSuccess()) {
                token= result.getData();
                System.out.println("PushToken:" + token);
            } else {
                System.out.println("PushToken Error:" + result.getException().getMessage());
            }
        });`

**Comment by ananth10** [comment]
Hi Team,

I could resolved this issue by removing this line from our code **Pushwoosh.getInstance().sendTags(Tags.intTag("app_fav_number", 42));**. I am getting token now.

**Comment by wfhm** [comment]
@ananth10,

This is very strange, sending Tags should not affect device registration. Could you please share a reproducer project so we could check it on our side?
