### ISSUE TITLE
summary notifications factory not working when i use both factory for single notification and summary factory

### ISSUE THREAD

**Issue by pdawiduk** [Pushwoosh/pushwoosh-android-sdk#138]
Nottifications display a single notification when i have definied factory both for a single and summary..
When i use summary factory notification displays like a standard notification not as custom view <-- missing handle

**Comment by wfhm** [comment]
@pdawiduk,

Just to be clear, am I correct that it is two separate issues?

1. When using both a Summary notification factory and a regular NotificationFactory, notifications are not grouped and are shown separately

2. Your custom layout is not applied to a generated Summary notification

Could you please describe both cases in a bit more details? It would really help if you could create a support ticket at https://help.pushwoosh.com/hc/en-us/requests/new and share a reproducer APK so we could try it on our side. At last, could you please share the code of your factories?
