### ISSUE TITLE
getLaunchNotification returns notification all the time

### ISSUE THREAD

**Issue by Pandan** [Pushwoosh/pushwoosh-android-sdk#14]
getLaunchNotification returns notification even if the application is not opened in response to push notification.
It's seems like it is returning the latest push notification that has been received.
Even if I call clearNotificationCenter the first time I receive a notification, it returns the latest push next time a call getLaunchNotification

```
@Override
protected void onStart() {
    super.onStart();

    String launchNotification = PushManager.getInstance(this).getLaunchNotification();
    if (launchNotificatin != null)
    {
        Log.d(“trace", "onStart Launch notification received: " + launchNotificatin);
         // Show alert dialog and stuff
        PushManager.clearNotificationCenter(this);
    }
    else
    {
        Log.d("trace", "onStart No launch notification received");
    }
}
```

**Comment by shaders** [comment]
fixed, see https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/Documentation/PushManager.md#clearlaunchnotification
