### ISSUE TITLE
startActivityForPushMessage not called if url is specified

### ISSUE THREAD

**Issue by enricoantonini84** [Pushwoosh/pushwoosh-android-sdk#140]
Hi,

I have an issue with the pushwoosh notifications on Android SDK.
We are scheduling a lot of notifications for our users via API calls, and we are trying to build a single notification for each user, that is receiveable on all devices types: Chrome, iOS, and Android. Every notification needs to have an URL, that the user can visit when tapping on it.
To achieve this, we have built a notification with action URL, with the URL specified and a customdata json, that we use to get additional data from our website.

This approach works well on iOS and Chrome, which handle the link in the correct manner, but not on Android. The problem on Android is that the URL is treated as a web URL, and every time a user taps on the notification the app asks the application that needs to be used to open the URL.

![Screenshot_20200325-144452](https://user-images.githubusercontent.com/60257681/77544288-1dfefd00-6ea9-11ea-8019-5dbe6879f9c1.png)

I have implemented a custom NotificationServiceExtension with the onMessageReceived method and the startActivityForPushMessage method as stated in https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/android-push-notifications/customizing-android-sdk-5.0#customising-notification-open-behaviour

The problem is that the startActivityForPushMessage is not called if an URL is provided, so I can't handle the notification as custom and avoid displaying the standard notification that asks the user to choose which application has to be used to open the link.
I know that we can simply send another kind of notification to our android user without the link, so the  startActivityForPushMessage can be called (that's the solution that we have implemented now to avoid the "open with" popup) and we can handle the custom URL, but I'm wondering if there is a way to get that method call even if there is an URL specified.

Thanks
Enrico

**Comment by wfhm** [comment]
Hi @enricoantonini84,

Please let me pull some time to see if there is a workaround.

**Comment by wfhm** [comment]
@enricoantonini84,

Could you please specify the SDK version you use in your project and send us an example of a link you use in your push notifications?

**Comment by enricoantonini84** [comment]
@wfhm we currently use the sdk version 5.22.2.
We usually set a link like 

https://www.bantoa.com/it/outfit-donna/focus/bella-anche-a-casa?utm_source=bantoa&utm_medium=notification&utm_campaign=notification_it_202003241335&utm_content=outfit-da-casa

and this as custom json data 

{"url":"https://www.bantoa.com/it/outfit-donna/focus/bella-anche-a-casa?utm_source=bantoa&utm_medium=notification&utm_campaign=notification_it_202003241335&utm_content=outfit-da-casa","data":"https://www.bantoa.com/it/outfit-donna/focus/bella-anche-a-casa?utm_source=bantoa&utm_medium=notification&utm_campaign=notification_it_202003241335&utm_content=outfit-da-casa"}

Thanks
Enrico

**Comment by wfhm** [comment]
@enricoantonini84

With the 5.22.4 SDK version we've added `preHandleNotificationsWithUrl` method. To make SDK always call startActivityForPushMesssage when an URL is passed you should return **false** as its value (return **true** for default behavior).
