### ISSUE TITLE
What happened to PushwooshFcmHelper?

### ISSUE THREAD

**Issue by HellerCommaA** [Pushwoosh/pushwoosh-android-sdk#142]
Unless my gradle settings are messed up, PushwooshFcmHelper seems to have been removed.

**Comment by wfhm** [comment]
Hi @HellerCommaA,

Could you please try to `import com.pushwoosh.firebase.PushwooshFcmHelper` in you app build.gradle?

**Comment by wfhm** [comment]
@HellerCommaA,

A quick follow-up here. The PushwooshFcmHelper class was moved to a separate lib, so you should also add it in your build.gradle:

`implementation 'com.pushwoosh:pushwoosh-firebase:6.0.0'`

**Comment by Svilcata19** [comment]
Well, I added it but I still cant see PushwooshFcmHelper.

**Comment by wfhm** [comment]
@Svilcata19,

Checking it.

**Comment by wfhm** [comment]
@Svilcata19, @HellerCommaA,

Got it reproduced. For some reason, the class gets obfuscated, ignoring applied proguard rules. We are working on the fix right now.

**Comment by wfhm** [comment]
Will be fixed with the next release.

**Comment by wfhm** [comment]
Fixed in 6.0.2.

**Comment by Svilcata19** [comment]
All good, thank you :)
