### ISSUE TITLE
PushwooshInbox.loadMessages empty response issue

### ISSUE THREAD

**Issue by LukaKit** [Pushwoosh/pushwoosh-android-sdk#144]
Hey.

We're noticing an issue regarding loading messages from PushwooshInbox.
After calling `PushwooshInbox.loadMessages(callback)`, our overridden `proces` function receives an empty list, but only on two devices (Moto G7, Android 9 and OnePlus A1, Android 6.01). All other devices receive the correct response (a filled list with messages), when fetching messages of the same user.
Both troublesome devices are receiving push notifications correctly, so the link with Pushwoosh should be working correctly.
Do you have any advice as to what to check? I can also provide you some additional info, if you need it.

**Comment by wfhm** [comment]
@LukaKit,

I could not reproduce the issue so far, so we'll need to check what is happening on these particular devices. This might require knowing the HWIDs of these two devices, and, to avoid exposing any sensitive data publicly, could you please create a support ticket at https://help.pushwoosh.com/hc/en-us/requests/new?

**Comment by LukaKit** [comment]
@wfhm Thank you. I'll open a ticket. 
Is there anything else besides the HWIDs that I should include in the attachments?

**Comment by wfhm** [comment]
@LukaKit,

HWIDs should be enough for now, thanks.

**Comment by LukaKit** [comment]
Thank you. I'll close this issue and continue there.
