### ISSUE TITLE
onTokenRefresh doesn't update token

### ISSUE THREAD

**Issue by KnYaZuK** [Pushwoosh/pushwoosh-android-sdk#146]
Version 6.0.2

After call method `PushwooshFcmHelper.onTokenRefresh(token)` inside FirebaseMessagingService `onNewToken(token: String)` - nothing happens

Tried use with Rx on io thread - result the same

Also tried versions 5.22.6, 6.0.3, 6.0.4

**Comment by wfhm** [comment]
Hi  @KnYaZuK,

Could you please share the code of your FirebaseMessagingService class? Also, is it registered in the AndroidManifest.xml, and, if yes, does it have the highest priority?
