### ISSUE TITLE
Huawei push kit support

### ISSUE THREAD

**Issue by megaacheyounes** [Pushwoosh/pushwoosh-android-sdk#148]
Hi, do you guys have any plans to add support for Huawei push kit https://developer.huawei.com/consumer/en/hms/huawei-pushkit.
Thanks.

**Comment by wfhm** [comment]
Hey! Yes we do!
If you are interested in it right now please hit us at help@pushwoosh.com

**Comment by wfhm** [comment]
@megaacheyounes,

Huawei pushes are currently in beta, if you want to participate, please hit us at https://help.pushwoosh.com/hc/en-us/requests/new. Native Android SDK already supports Huawei Push Kit, so I am closing the issue in this repo. An official release will be publicly announced later.
