### ISSUE TITLE
PushwooshInApp deprecated - how to post event?

### ISSUE THREAD

**Issue by candeiasdan** [Pushwoosh/pushwoosh-android-sdk#149]
I am upgrading from Pushwoosh version 5.* to 6.1.0, and I get `PushowooshInApp` class deprecated. 

Previously I would use `PushwooshInApp.getInstance().postEvent("myCustomEvent");`, but now the class is deprecated.How can I post an event without using deprecated class?

Office Pushwoosh page still recommends to use the old `PushwooshInApp`: https://docs.pushwoosh.com/platform-docs/automation/behavior-based-messaging/events#android

**Comment by wfhm** [comment]
Try `InAppManager.getInstance().postEvent(appOpen)` (from com.pushwoosh.inapp.InAppManager).
