### ISSUE TITLE
Send extra tracking parameters on In-App Messaging

### ISSUE THREAD

**Issue by candeiasdan** [Pushwoosh/pushwoosh-android-sdk#150]
Is there a way to send extra tracking data after user rating the app? 
Do we have any control over In-app messaging screen?

**Comment by wfhm** [comment]
@candeiasdan hey, may I ask you to describe your use-case in a bit more detail? What kind of control do you want to have over the In-App screen?

**Comment by candeiasdan** [comment]
The default In-App message for rating already sends the parameter `rating`. I would like to send as well some other values like user country, language, etc, so I can filter ratings by those extra parameters.

**Comment by wfhm** [comment]
@candeiasdan,

It is possible, however, you will need to create a custom Rich Media for that. You can download our default In-App and modify its code to send a /postEvent request with your custom Event that has several different parameters. For example, just modify the JS script of our default Rate My App In-App:

                if (window.pushManager) {
                    window.pushManager.postEvent(JSON.stringify({
                        event: 'send_rating',
                        attributes: {
                            rating: rate,
                            country: country,
                            language: language
                        }
                    }));

Archive the rich media and upload it to Pushwoosh, then create a new Event with the name and attributes you specified in your code. Then, create an In-App based on the new event and the new Rich Media.
