### ISSUE TITLE
PostEvent retry policy

### ISSUE THREAD

**Issue by serveravt** [Pushwoosh/pushwoosh-android-sdk#152]
is this API InAppManager.getInstance().postEvent("eventName") has some retry policy? 
Will event be delivered after internet connection on device will be restored?

**Comment by wfhm** [comment]
@serveravt,

Adding retry policy to all types of failed requests is in our backlog for the first quarter of 2021. I will update this thread when it is committed to development.

**Comment by wfhm** [comment]
@serveravt we have decided not to implement retries for postEvent, as this request is not idempotent.
