### ISSUE TITLE
Pushwoosh.language throws NullPointerException

### ISSUE THREAD

**Issue by svrlopatrik** [Pushwoosh/pushwoosh-android-sdk#160]
I've upgraded pushwoosh android sdk from version 5.22.3 to latest 6.2.7 because of new Google Developer program privacy policy and now I'm facing NullPointerException when setting pushwoosh's language:

```
pushwoosh.apply {
        language = "en"
        appId = "..."
        sendTags(Tags.stringTag(NOTIFICATION_TAG_ID, "..."))

        registerForPushNotifications {
          if (it.isSuccess) {
            ...
          } else {
            ...
          }
        }
      }
```

`java.lang.NullPointerException: Attempt to invoke virtual method 'void com.pushwoosh.repository.RegistrationPrefs.setLanguage(java.lang.String)' on a null object reference`

How can I solve this issue?

**Comment by nikolleto** [comment]
@svrlopatrik, have you added 'pushwoosh-firebase' module to your dependencies as it noted in the migration guide? 
https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/android-push-notifications/customizing-android-sdk/migration-guide

**Comment by svrlopatrik** [comment]
Oh, I didn't notice that, thank you. It helped solve the issue.
