### ISSUE TITLE
Removed app update being rejected by Google

### ISSUE THREAD

**Issue by Mempz** [Pushwoosh/pushwoosh-android-sdk#161]
Hello, we've read here that we need to update our pushwoosh sdk to version 6.2.7 after our app has been removed from the Google PlayStore due to privacy issues: https://github.com/Pushwoosh/pushwoosh-android-sdk/issues/159

![image](https://user-images.githubusercontent.com/20332590/115112670-2ac12800-9fb9-11eb-92eb-bab143f4c653.png)

We've already updated the sdk version but Google still rejects our app submissions due to the same reason.

Are we doing something wrong here? Because our app has been out of the store for a week now and will cause us major problems if it continues to do so.

**Comment by bsquang** [comment]
Yes, same here. PUSHWOOSH please to take care this ! My client so angry for this happen, i have re-up 5 times and rejected 5 times !

**Comment by wfhm** [comment]
@Mempz @bsquang 

Could it be that you have APKs/AABs with the older version of Pushwoosh SDK in other releases (not just the latest production one but in alpha-, beta-, or internal testing tracks), or if multiple APKs are included in the active releases?

**Comment by Mempz** [comment]
@wfhm that could be the case. Should we upload separate builds with the updated SDK for each track?

**Comment by wfhm** [comment]
@Mempz,

Since you have to create new releases for each track, yes, you should upload separate builds with the updated SDK for all tracks. If your release includes multiple APKs, make sure that all APKs comply with the new Google Play policy (built with the latest Pushwoosh SDK).

**Comment by Mempz** [comment]
Thank you, I'll post an update once we receive a response from Google.

**Comment by HassanImtiaz** [comment]
Does this issue exists for 5.22.2?

**Comment by Mempz** [comment]
> Does this issue exists for 5.22.2?

I think most, if not all, apps that are using the old versions of Pushwoosh have encountered this problem. It'd be better if you upgrade now even if Google hasn't warned you yet.

**Comment by HassanImtiaz** [comment]
Thanks for the reply. We are going to upgrade to 6.2.7. Does Google notifies app developer before removing the app? or they are straightaway removing apps from play store?

**Comment by wfhm** [comment]
> Does Google notifies app developer before removing the app? or they are straightaway removing apps from play store?
They stated that they will give all existing apps 30 days grace period, but some of our clients reported that they were only given with a week to update SDK, and some other clients had their app removed from Play Market without any warning.

**Comment by piotr-marat** [comment]
> @wfhm that could be the case. Should we upload separate builds with the updated SDK for each track?

**Comment by piotr-marat** [comment]
@Mempz any luck ? I have the same issue: app rejected twice after upgrading to 6.2.7 after being removed without any warning.

**Comment by Mempz** [comment]
> @Mempz any luck ? I have the same issue: app rejected twice with 6.2.7 after being removed without any warning. In my case it's react native plugin (6.1.5 with 6.2.7 sdk).

@piotr-marat before I opened this issue, we temporarily removed the sdk from the build then submitted it. After its approval we then went on to submit a new build with the updated pushwoosh sdk on it in the Internal testing track. So far, it's been two days since then and we haven't received any warning about it.

**Comment by piotr-marat** [comment]
@Mempz Thanks. Sounds like a good idea. I'll try this.

**Comment by piotr-marat** [comment]
@Mempz It did not help, in my case - app has been rejected even without PushWoosh SDK. I have sent the appeal Google Play and now waiting again.

**Comment by Mempz** [comment]
> @Mempz It did not help, in my case - app has been rejected even without PushWoosh SDK. I have sent the appeal Google Play and now waiting again.

@piotr-marat did you also submit an update on the production track?

**Comment by piotr-marat** [comment]
@Mempz no, I tried only with internal path (version without Pushwoosh), but before i tried all paths with latest Pushwoosh - same result, rejection
