### ISSUE TITLE
Explicitly specify android:exported for every components in manifest

### ISSUE THREAD

**Issue by elliemehrganrad** [Pushwoosh/pushwoosh-android-sdk#164]
As one of the changes on apps targeting Android 12, it is forced to explicitly specify android:exported for every components containing `intent-filter` in manifest. 

Targeting Android 12 we get manifest merge conflict caused by Pushwoosh SDK 6.2.8

**Comment by wfhm** [comment]
@elliemehrganrad

Right now Pushwoosh SDK does not support Android 12 - changes to component exporting, pending intents mutability, and new notification trampoline restrictions break our SDKs functionality, so we will have to release a new version that will work on Android 12. This is already in our backlog and will be done in the nearest future.

**Comment by wfhm** [comment]
@elliemehrganrad Android 12 is supported starting with 6.3.0.

**Comment by elliemehrganrad** [comment]
@wfhm Thank you so much for letting me know.
