### ISSUE TITLE
Fix inherited platform declarations clash

### ISSUE THREAD

**Issue by elliemehrganrad** [Pushwoosh/pushwoosh-android-sdk#165]
We are using `InboxActivity` in our app, targeting or compiling against Android API Level 30, we get the following exception on `InboxActivity`:

`Inherited platform declarations clash: The following declarations have the same JVM signature (onOptionsItemSelected(Landroid/view/MenuItem;)Z):
    fun onOptionsItemSelected(p0: MenuItem): Boolean 
    fun onOptionsItemSelected(item: MenuItem?): Boolean`

**Comment by wfhm** [comment]
@elliemehrganrad Will be fixed with the next release.

**Comment by wfhm** [comment]
Fixed in 6.2.9.

**Comment by elliemehrganrad** [comment]
> Fixed in 6.2.9.

Thanks for your prompt action 👍
