### ISSUE TITLE
Show multiple notifications instead of a single one

### ISSUE THREAD

**Issue by RuiEEE** [Pushwoosh/pushwoosh-android-sdk#171]
I've been trying to make it so pushwoosh shows separate notifications, for some reason, whenever I receive a push notification, the previous one is overrided.

I've seen mentions of [multiNotificationMode](https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/Documentation/PushManager.md#setmultinotificationmode) which apparently no longer exists.

I've tried to manually generate my own pushes, by notifying with different IDs, but like [this comment](https://github.com/Pushwoosh/pushwoosh-android-sdk/issues/49#issuecomment-456048460) mentions, if I do that, I don't have statistics of app opens on the backoffice.

Is this even achievable?
I'm using latest version of pushwoosh.
`implementation 'com.pushwoosh:pushwoosh:6.3.0'`
`implementation 'com.pushwoosh:pushwoosh-firebase:6.3.0'`

**Comment by wfhm** [comment]
Hi @RuiEEE

Please find the setMultiNotificationMode method in com.pushwoosh.notification package, PushwooshNotificationSettings class

https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/Documentation/notification/PushwooshNotificationSettings.md#public-static-void-setmultinotificationmodeboolean-on

**Comment by RuiEEE** [comment]
Got it. Also got it working.
Thanks, I was really having a hard time finding that setting. I don't think I saw mention of those settings in the documentation.
