### ISSUE TITLE
Question: is PushWoosh allowed in the Family Program of Google?

### ISSUE THREAD

**Issue by jasperrietrae** [Pushwoosh/pushwoosh-android-sdk#172]
Good evening everyone,

We have an active app in the store using OneSignal to send pushnotifications. Since a few months now, Google has opted to reject any app in the family program that is using OneSignal. It's been taking really long for Google to change this, so we have to look into alternatives. Is there any certainty that Google doesn't reject PushWoosh?

Best regards

**Comment by wfhm** [comment]
Hey @jasperrietrae,

We have never heard about such rejections from our customers. However, to be sure that it won't happen in the future, can you share the exact message from Google with the reason for rejection? They usually provide a short description of violations that caused the rejection.

**Comment by jasperrietrae** [comment]
@wfhm excuse me, I was unable to respond timely. Here's the message:

```
We have detected that your app includes non-certified ad SDKs and/or SDKs that are not approved for use in child-directed services. Any SDKs used in the app must be appropriate for use in child-directed services. Additionally, apps that solely target children must not contain any SDKs that are not approved for use in child-directed services, including ads SDKs. Apps in the Designed for Families program must only use ad SDKs that have certified their compliance with the Families Ads Program.
We have detected the use of OneSignal, which is not allowed in apps that are in the Families program. An ad SDK is not allowed if it is an ad SDK that has not self-certified its compliance with Play’s Families Ads Program (certified ad SDKs), or, even if it is not an ad SDK, it is not approved for use in child-directed services non-COPPA compliant per its own public documentation (unless, for apps that target both children and older audiences, it is used behind a neutral age screen or implemented in a way that does not result in the collection of data from children). SDKs that have not self-certified their compliance with Play’s Families Ads Program (certified ad SDKs) and SDKs that are not approved for use in child-directed services per their own public documentation cannot be used to serve children or users of unknown age. These SDKs may be allowed if they are used behind a neutral age screen or implemented in a way that does not result in the collection of data from children. Please note, the status of SDKs often changes and it is your responsibility to review documentation of all SDKs used in your app to ensure compliance with Families policies.
```

**Comment by wfhm** [comment]
@jasperrietrae,

Our SDK has not self-certified its compliance with Play's Families Ads Program, so we cannot guarantee there will be no issues with publishing the app to the store. I have discussed your case with our management, and we will check if we can mark our SDK as COPPA-compliant (if I understood it correctly, this is the reason Outsystems SDK gets rejected) and get back to you with the news.

**Comment by jasperrietrae** [comment]
@wfhm thanks, eager to hear back from you!

**Comment by wfhm** [comment]
@jasperrietrae 

We were unable to confirm that our SDK can be safely used in applications participating in the "Designed for Families" program as none of our current demo applications fit the requirements of the program, and creating a new app that will conform to all Family Program rules is something we will not be able to do in the nearest future. 

However, with the 6.2.4 release, we have added a new flag that disables collection of all user and device data, so there is a good chance it will not be a cause for rejection. To disable collecting this data, just add the following meta-data to your AndroidManifest.xml:

```
        <meta-data
            android:name="com.pushwoosh.allow_collecting_device_data"
            android:value="false"/>
```

**Comment by jasperrietrae** [comment]
@wfhm it sems like the latest 6.2.4 change actually was all we needed.. we just got rejected for a different reason, instead of being auto-rejected just for using the dependency in the family program.

**Comment by wfhm** [comment]
@jasperrietrae That sounds promising! If that's not too much to ask, we would really appreciate it if let us know if you make it to the store with the 6.2.4 version, so we could help other users with similar cases. Meanwhile, we'll keep this issue closed, as there is not much we can do from our side right now.

**Comment by jasperrietrae** [comment]
@wfhm sadly, Google keeps rejecting our app even with PushWoosh. :-(
