### ISSUE TITLE
Pushwoosh Android isn't receiving notifications very first time.

### ISSUE THREAD

**Issue by nmssalman** [Pushwoosh/pushwoosh-android-sdk#173]
In the android application with latest version of pushwoosh, when i install the app and open it, it's successfully registered for notifications, but i don't get the notification in the very firs time. i have to at least restart once the app to start receiving notifications.

**Comment by wfhm** [comment]
Hi @nmssalman,

I could not reproduce the issue so far, so, by any chance, can you share a reproducer project with us (or, if the issue is reproducible with the sample app, provide us with the steps to reproduce it)?
