### ISSUE TITLE
Android 11 notification sounds aren't working

### ISSUE THREAD

**Issue by nmssalman** [Pushwoosh/pushwoosh-android-sdk#174]
I'm using pushwoosh notifications for several android platforms and all are working good. but in android 11, pushwoosh has some issues, i'm only getting notification and it's not been able to play the sound in raw -> sound file. it's working smoothly in android 7,8,10 and we are facing this only for android 11. anyone can help me out? we are using all the pushwoosh latest libraries.

**Comment by wfhm** [comment]
@nmssalman I just tried to reproduce the issue with the latest SDK version, and the sound worked perfectly on Android 11 (Pixel 2 API 30 emulator and Pixel 3xl real device). Could you please share a reproducer project with us so we could try it on our side?
