### ISSUE TITLE
Android 12 support 

### ISSUE THREAD

**Issue by DevDin** [Pushwoosh/pushwoosh-android-sdk#175]
Hi,
After our users updating their devices to Android 12, our app is crashing. We use pushwoosh in our App.'
Pls test and update your SDK to support Android 12:
here is the link that can help you get started: [migrating to Android 12](https://medium.com/tech-takeaways/migrating-my-app-to-android-12-7bafba3ed999#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ0ZTA2Y2ViMjJiMDFiZTU2YzIxM2M5ODU0MGFiNTYzYmZmNWE1OGMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2MzgzNjAyODUsImF1ZCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExODE4Njk4MTk0NzI2MzUwMjg0NiIsImVtYWlsIjoiZGV2ZWxvcGVyLmRpbmVzaDA0MkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiMjE2Mjk2MDM1ODM0LWsxazZxZTA2MHMydHAyYTJqYW00bGpkY21zMDBzdHRnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwibmFtZSI6IkRpbmVzaCBEZXZlbG9wZXIiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EtL0FPaDE0R2cwX0hYcHpFeFI4NmhDZHh5SldQT2MtMTN4cGZIMzFvU3llNU5XPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6IkRpbmVzaCIsImZhbWlseV9uYW1lIjoiRGV2ZWxvcGVyIiwiaWF0IjoxNjM4MzYwNTg1LCJleHAiOjE2MzgzNjQxODUsImp0aSI6ImZiMTI3MjQzZDgyMThhYWViZDZmZDdlOWQyOTkyMzg3ZDAwNDA0OTEifQ.KKTRGbo7DIB4yIUJYxzZd5milduOqSzUn_fyYZuez2UWmmepGW9NGjAiQuB495plbqmyiCZ76HZTg_pSYeiegwEfOqz1OW3j6FTByiktA6KcJnBn-8G0icPdp0kkPMFpXTta1BGBw_A3Dv3JsaSSfXfMA00DCkSfA1lJ9Z_ON65zatwMP0iNPDRlgqElD5z5MccOmptWl6Y_3edahE6-9ifJ4JFVcSZdTujLtIwFDHVdPHK5O9LFjUcGiRu2YJxz6Fi1J1S5wAYAMj1APrKq_ObC4vaAIScOK-NEJZ_fV56z85RS7sNhNQbfnO5rgjT5gV0PUTrnWWblD3Dy80mzVA)

java.lang.IllegalArgumentException: com.xx.xx: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:285)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:158)
        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:185)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:103)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

**Comment by wfhm** [comment]
Hi @DevDin,

Pushwoosh SDK supports Android 12 starting with the 6.3.0 version, and all Activities, receivers, and services were labeled with the `FLAG_IMMUTABLE` flag. **pushwoosh-location** module supports Android 12 starting with the 6.3.2 version. Could you please let us know what SDK version is used in your project?

Also, what exactly points to Pushwoosh SDK in your app when this error appears? What particular activities, services, or receivers are mentioned in the build log?

**Comment by DevDin** [comment]
I'm using 6.3.5 (i guess it is very latest.). I found that your SDK depends on androidx.work:work-runtime & you need to update this dependency to 2.7.0 . pls check once.

**Comment by DevDin** [comment]
It worked after i adding this patch:
//PushWoosh
    implementation 'com.pushwoosh:pushwoosh:6.3.5'
    constraints {
        implementation('androidx.work:work-runtime:2.7.0') {
            because 'pushwoosh sdk  depends on work-runtime:2.6.0 which is not compatible with targetSdk 31, but work-runtime:2.7.0 is'
        }
    }

**Comment by wfhm** [comment]
@DevDin Thanks, indeed we have to update work-runtime dependency. It will be done with the next release.

**Comment by wfhm** [comment]
Fixed with the latest update.
