### ISSUE TITLE
App rejection

### ISSUE THREAD

**Issue by robhanaway** [Pushwoosh/pushwoosh-android-sdk#176]
Hi there,
I recently received an app rejection from the play store, I'm using:
    com.pushwoosh:pushwoosh 6.3.5
and
    com.pushwoosh:pushwoosh-firebase 6.3.5

**

> APK REQUIRES PROMINENT DISCLOSURE​
> We’ve identified that your app is using Pushwoosh SDK or library, which facilitates the transmission of collection of Installed application information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information.

**

Wasn't this resolved in version 6.2.7 as related to in this issue:
https://github.com/Pushwoosh/pushwoosh-android-sdk/issues/159

**Comment by wfhm** [comment]
@robhanaway This indeed was resolved with the 6.2.7 release. Could it be that you have older Pushwoosh SDK versions implemented in non-production tracks in the Google Play Console (i.e. in your alpha- or beta-testing tracks)? You can refer to step 3 of the following guide for additional details: 

https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/android-push-notifications/compliance-with-google-package-visibility-policy

**Comment by robhanaway** [comment]
@wfhm Yes, this seems to be the issue.
Thank you for the quick feedback.
