### ISSUE TITLE
Prevent sdk from calling home(/registerUser) before user has opted in to the privacy policy

### ISSUE THREAD

**Issue by lwky** [Pushwoosh/pushwoosh-android-sdk#179]
Hi, we'd like to disable pushwoosh from doing any requests until the user has agreed to the privacy policy in the app.
By not setting `com.pushwoosh.appid` in the manifest but setting it through `Pushwoosh.getInstance().setAppId()` we can delay the calls to `getConfig, getInApps, applicationOpen`. However, `registerUser` is always called, even though it results in a 210, probably because the appid is not set.

on app start before onCreate:
```
Pushwoosh: [RequestManager] Try To send: registerUser; baseUrl: https://cp.pushwoosh.com/json/1.3/

Pushwoosh request:
Url: https://cp.pushwoosh.com/json/1.3/registerUser
Payload: {"request":{"application":"","hwid":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","v":"6.6.0","device_type":3,"userId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}}
Response: {"status_code":210,"status_message":"application code is not valid","response":null}
```

Is there any way to prevent this call from being executed?

**Comment by wfhm** [comment]
@lwky Sure, you can use the `com.pushwoosh.allow_server_communication="false"` meta-data flag to your manifest. If set to **false,** this flag disallows to send network requests to Pushwoosh servers until server communications are turned on by a user. Then, to allow sending requests, just call `Pushwoosh.getInstance().startServerCommunication()`.
