### ISSUE TITLE
java.io.FileNotFoundException: http://cp.pushwoosh.com/json/1.3/registerUser

### ISSUE THREAD

**Issue by vlad1m1r990** [Pushwoosh/pushwoosh-android-sdk#18]
I am getting following error:

E/Pushwoosh﹕ [RequestManager] ERROR: http://cp.pushwoosh.com/json/1.3/registerUser. Response = null
java.io.FileNotFoundException: http://cp.pushwoosh.com/json/1.3/registerUser at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
            at com.pushwoosh.internal.request.RequestManager.makeRequest(Unknown Source)
            at com.pushwoosh.internal.request.RequestManager.sendRequestSync(Unknown Source)
            at com.pushwoosh.PushManager.registerUserInternal(Unknown Source)
            at com.pushwoosh.PushManager.access$000(Unknown Source)
            at com.pushwoosh.PushManager$1.run(Unknown Source)

Does anyone knows what could be a problem?

**Comment by shaders** [comment]
Does this happen all the time? Should work now.

**Comment by vlad1m1r990** [comment]
It's happening every minute or so. It's seems that some back process is not working properly.

**Comment by shaders** [comment]
can you paste full console logs?

**Comment by vlad1m1r990** [comment]
08-19 14:41:55.646  W/Pushwoosh﹕ [RequestManager] Try To sent: registerUser
08-19 14:41:55.651  W/Pushwoosh﹕ [RequestManager] Pushwoosh Request: {"request":{"v":"3.0.1.529","hwid":"836e64d7acad8701","userId":"836e64d7acad8701","application":"FA627-F8261"}}
08-19 14:41:55.651  W/Pushwoosh﹕ [RequestManager] Pushwoosh Request To: http://cp.pushwoosh.com/json/1.3/registerUser
08-19 14:41:55.651  I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false
08-19 14:41:55.671  I/System.out﹕ KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-19 14:41:55.741  E/Pushwoosh﹕ [RequestManager] ERROR: http://cp.pushwoosh.com/json/1.3/registerUser. Response = null
    java.io.FileNotFoundException: http://cp.pushwoosh.com/json/1.3/registerUser
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
            at com.pushwoosh.internal.request.RequestManager.makeRequest(Unknown Source)
            at com.pushwoosh.internal.request.RequestManager.sendRequestSync(Unknown Source)
            at com.pushwoosh.PushManager.registerUserInternal(Unknown Source)
            at com.pushwoosh.PushManager.access$000(Unknown Source)
            at com.pushwoosh.PushManager$1.run(Unknown Source)


This is the part that is repeating.

**Comment by vlad1m1r990** [comment]
I don't know what have you done but it's working now. :)

**Comment by shaders** [comment]
It's a temporary workaround and it will be removed soon, you'll need to update Pushwoosh Android SDK. Buildserver is baking one right now.

**Comment by shaders** [comment]
The reason is you are calling http API (which is deprecated) and new functionality requires using https only. However due to small issue with new SDK it didn't force-switch to https. The next build will.

**Comment by vlad1m1r990** [comment]
App is using very old API and now I am updating it. So I get this error with last version. Could it be that server side uses old version of API?

**Comment by shaders** [comment]
You can try the new build (3.1.2). Please also check the android updated guides as you need to change Android Manifest:
http://docs.pushwoosh.com/docs/androidmanifestxml-modifications

and Add Google Play Services LIbrary and Android Support v4.
http://docs.pushwoosh.com/docs/native-android-sdk

**Comment by vlad1m1r990** [comment]
And one more question, what happened with PushGCMIntentService class? What should I use as a replacement?

**Comment by shaders** [comment]
It's now served by this services:

```
<service
    android:name="com.pushwoosh.GCMListenerService"
    android:exported="false">
    <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
    </intent-filter>
</service>

<service
    android:name="com.pushwoosh.GCMInstanceIDListenerService"
    android:exported="false">
    <intent-filter>
        <action android:name="com.google.android.gms.iid.InstanceID"/>
    </intent-filter>
</service>

<service
    android:name="com.pushwoosh.GCMRegistrationService"
    android:exported="false">
</service>
```

**Comment by vlad1m1r990** [comment]
In older version I was able to customize notification, and now I can't do that. There is no Context inside onMessageReceived.

**Comment by shaders** [comment]
There's another way to do this now. It's much easier now. I'll post a guide tonight about this.

**Comment by shaders** [comment]
Take a look here:
http://docs.pushwoosh.com/v1.0/docs/android-faq#customizing-push-notifications

Let me know if you have any questions.
