### ISSUE TITLE
Android 14 support

### ISSUE THREAD

**Issue by antonio-c-ones** [Pushwoosh/pushwoosh-android-sdk#183]
<img width="524" alt="image" src="https://github.com/Pushwoosh/pushwoosh-android-sdk/assets/66253061/cbc4674e-b7a6-4e84-ab53-2c50b43c4435">

Regarding the most recent iteration, Beta 4, of Android 14's release, is there a strategy in place to provide compatibility for the push notification service offered by Pushwoosh? We are currently encountering a persistent application crash issue related to Pushwoosh while undertaking the migration process to Android 14.

**Comment by enginseer-dev** [comment]
@antonio-c-ones We are working on Android 14 support and will update you as soon as we have implemented the necessary changes and ensured compatibility with the new version of Android.

**Comment by enginseer-dev** [comment]
Hello, @antonio-c-ones.
We have released an updated version of our SDK, which now supports Android 14.
Please update to version 6.6.16 

Should you have any further questions or require assistance during the update, please don't hesitate to reach out.
