### ISSUE TITLE
StatusBar notifications bug

### ISSUE THREAD

**Issue by KorneliuszBarwinski** [Pushwoosh/pushwoosh-android-sdk#184]
Steps to reproduce:
1. We send  at least 3 notifications. (they will group as expected)
2. We expand the notification group.
3. We click on the first notification in the list (it opens correctly).
4. We click on the group (the previous, first notification opens).

I made a small research and it looks like the notifications from pushBundleDB are note deleted correctly. 
In function onMessagesGroupOpened(final List<PushMessage> messages) in NotificationServiceExtension.java i am getting a list of all notifications all the time. I tried this in my project and also on demo project from this repository.

**Comment by wfhm** [comment]
@KorneliuszBarwinski Thanks for reporting this! I'll take a look and get back to you shortly.

**Comment by KorneliuszBarwinski** [comment]
@wfhm Can i have update on the situation?

**Comment by enginseer-dev** [comment]
Hello, @KorneliuszBarwinski

Thank you for your patience. 
We've successfully reproduced the issue and our team is investigating it. 

We'll keep you posted with any updates.

**Comment by KorneliuszBarwinski** [comment]
Hi, @enginseer-dev 
Can i have update?

**Comment by enginseer-dev** [comment]
Hello, @KorneliuszBarwinski 

Our team is currently working on a new grouping logic for the notifications.
After it's finished and tested we will update you.

**Comment by wfhm** [comment]
Hi @KorneliuszBarwinski 

Got it reproduced, will be fixed with the new release.

**Comment by wfhm** [comment]
@KorneliuszBarwinski fixed in 6.7.5.
