### ISSUE TITLE
[Question]: Could not HEAD Received status code 502 from server: Bad Gateway

### ISSUE THREAD

**Issue by sergeymild** [Pushwoosh/pushwoosh-android-sdk#185]
### Documentation

- [X] I've checked the guide, but I didn't find the information I needed there.

### Question

Could not HEAD 'https://oss.sonatype.org/content/repositories/snapshots/com/pushwoosh/pushwoosh-firebase/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

<img width="1614" alt="Screenshot 2024-01-16 at 08 42 00" src="https://github.com/Pushwoosh/pushwoosh-android-sdk/assets/3685209/2fd9ad0c-a91e-4b98-876f-4a87175056e5">

**Comment by enginseer-dev** [comment]
Hello!

It looks like maven repository had some accessibility issues, and libraries hosted there were not available for downloading.
The issue is now resolved, so may I ask you to try again and let me know if the issue persists?

**Comment by enginseer-dev** [comment]
@sergeymild Thank you for a quick update! 
Have a great week!
