### ISSUE TITLE
Saving custom data on notification launch time

### ISSUE THREAD

**Issue by DevendraSingh91** [Pushwoosh/pushwoosh-android-sdk#20]
Hi PushWoosh Team,
My app requirement is "Save the data,receiving in the notification."  Second I want to open the desired activity onClick of notification.
Currently I can store the data only on that activity in 
 BroadcastReceiver mBroadcastReceiver = new BaseRegistrationReceiver() {
        @Override
        public void onRegisterActionReceive(Context context, Intent intent) {
            checkMessage(intent);
        }
    };
    private String data;
    private BroadcastReceiver mReceiver = new BasePushMessageReceiver() {
        @Override
        protected void onMessageReceive(Intent intent) {
            //JSON_DATA_KEY contains JSON payload of push notification.
            //showMessage("push message is " + intent.getExtras().getString(JSON_DATA_KEY));
            data = intent.getExtras().getString(JSON_DATA_KEY);
       //*******Storing opration
            } catch (JSONException e) {
                e.printStackTrace();
            }
        }
    };
but i want to store the data from anywhere even i am out of the app. but if the notification has been generated the data must be store in Sqlite.
Please suggest and help me what should i do?
Thanks

**Comment by shaders** [comment]
I would recommend using Custom Broadcast Receiver, which is triggered each time push notifications has been received. This way you can store each and every push notification in the database.
You don't have to specify BasePushMessageReceiver then, but you have to perform action to open your app (which should be pretty simple).

Take a look here:
http://docs.pushwoosh.com/docs/android-faq#using-custom-push-broadcast-receiver-in-android

**Comment by vvvpoornima** [comment]
Hello,
I just integrate pushwoosh android jar file and i did all step and i also validated my manifest file but app is crashing on 2nd line of oncreate method
pushManager = PushManager.getInstance(BrowserActivity.this);

Please tell me where i am wrong or some problem in sdk 

Thanks

**Comment by shaders** [comment]
Please provide logs of the crash from the device

**Comment by chetan136** [comment]
hello, 
I have made all changes as you said for saving notification in local database, but in my app custom receiver not fire when new notification arrive and app is close. but when i click  on notification then custom receiver fire. 

I want to save notification in database when app is close and notification arrives. 

Please suggest and help me.

**Comment by DimanAM** [comment]
Notification arrival can be handled in ```onPushReceived``` method of *AbsNotificationFactory* 

See
http://docs.pushwoosh.com/docs/android-faq#customizing-push-notifications
https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/Documentation/AbsNotificationFactory.md#onpushreceived

**Comment by chetan136** [comment]
hello DimanAM,
I have added that NotificationFactorySample code and also set it with pushmaneger, but it's not called onPushReceived methode.

is their any changes required in manifest file ? and also can i use both custom broadcast receiver and NotificationFactorySample in application.

**Comment by chetan136** [comment]
Thank you so much.
It's really  useful for me. it's working fine.
