### ISSUE TITLE
Misleading gradle advice in docs 

### ISSUE THREAD

**Issue by divyenduz** [Pushwoosh/pushwoosh-android-sdk#22]
The docs advise to use the below gradle line to add pushwoosh as a dependency. 
`compile 'com.pushwoosh:pushwoosh:+'`

But using `+` in mentioning a gradle dependency is not advisable as the client may not realize that his library has updated. 
So, the code may go between two incompatible version and since it is push notification, the client may ship the app with his push notification in a inconsistent state.

Moreover, it is too hard to find the latest released SDK version as of now. My suggestion is that the docs always suggest the latest stable version and mention any migration paths between two versions.

Please let me know if I am missing any point.

Thanks and regards
Divyendu Singh

**Comment by shaders** [comment]
Sure you are right and you can always use it like:

   compile 'com.pushwoosh:pushwoosh:3.1.8'

You can get the version of the SDK from the VERSION.md file:
https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/VERSION.md

or from maven repo:
http://search.maven.org/#search%7Cga%7C1%7Cpushwoosh

**Comment by divyenduz** [comment]
Is there a doc that tells me migration process from 2.9.14 to 3.1.8 ?
I replaced these two and the project did not compile. PushManager and a couple of more classes have gone out of the window it seems.

**Comment by shaders** [comment]
What kind of errors do you receive?

**Comment by divyenduz** [comment]
The app does not compile as it fails to find PushManager and some other classes.

**Comment by shaders** [comment]
Could you provide the exact errors?

**Comment by divyenduz** [comment]
Sure, so, when I use `compile 'com.pushwoosh:pushwoosh:3.1.8'` in place of compile `'com.pushwoosh:pushwoosh:2.9.14'`

I get the error that the following packages do not exist:

1. `com.arellomobile.push`
2. `com.arellomobile.push.utils`
3. `com.arellomobile.push.request`

Also, it fails to find the following classes (because the packages are no longer present):

1. PushGCMIntentService 
2. SendPushTagsCallBack
3. PushManager

Please advice. Thanks.

**Comment by divyenduz** [comment]
Hi, just checking, if you missed this because of this being closed ?

**Comment by shaders** [comment]
I would recommend redoing the integration using the latest android guide.
http://docs.pushwoosh.com/docs/native-android-sdk

The package names has been changed, actually Eclipse can fix most of this errors automatically.
