### ISSUE TITLE
Local notifications AlarmReceiver - UIThread.

### ISSUE THREAD

**Issue by localhostEU** [Pushwoosh/pushwoosh-android-sdk#25]
I want onGenerateNotification from AbsNotificationFactory to be executed on non UiThread.
 I know AlarmReceiver's onReceive method is called on UiThread - which give me no possibility to process some async work (for example get Image for notification icon from backend).

Is there any workaround for this or is there any chance you will refactor AlarmReceiver to start IntentService instead of directly interacting with AbsNotificationFactory in future?

**Comment by shaders** [comment]
Good point. I'll see what I can do. Will reply as soon as I get more info.
