### ISSUE TITLE
unregisterForPushNotifications() bugged.

### ISSUE THREAD

**Issue by localhostEU** [Pushwoosh/pushwoosh-android-sdk#27]
After calling this method (when user logs out for example), even if i call 
```
onStartup()
sendTags()
registerForPushNotifications()
```
device doesn't receive push messages anymore.
Happens on many different devices and emulators.

The only one solution is to remove app and install it again.
As a temporary solution i don't call `unregisterForPushNotifications()` on user logout, but you need to fix it asap.

**Comment by shaders** [comment]
Hi,

Fixed!

**Comment by localhostEU** [comment]
@shaders no commit yet?

**Comment by FallDi** [comment]
@localhostEU issue fixed on backend side and not require update mobile SDK

**Comment by localhostEU** [comment]
Thanks!

**Comment by localhostEU** [comment]
I think there are still some problems on your backend.
If logged user updates app - it can't receive pushes anymore until it remove app and install from market/adb.

**Comment by FallDi** [comment]
I will investigate the problem and will inform you about the results!

**Comment by FallDi** [comment]
@localhostEU  Hm, it really strange behaviour. 

I call setTags api method and then registerDevice with same hwid & pushtoken. In result device registered.

Can you provide SDK which you use?  And if possible logs from device?

**Comment by localhostEU** [comment]
Device registers, all is fine. 
But it doesn't receive pushes.
Getting same callbacks (in logcat) as when device gets push messages.
Using 3.4.0.

**Comment by DimanAM** [comment]
> Getting same callbacks (in logcat) as when device gets push messages.
What do you mean by this? You see messageDelivery and pushStat requests in logcat and there is no notification?
What is the exact log?

**Comment by localhostEU** [comment]
registerUser OK
applicationOpen OK
setTags OK
registerDevice OK
Registered for pushed: device_gcm_id

**Comment by shaders** [comment]
Can you provide full logs from the console? You can use Pastebin or similar.

**Comment by localhostEU** [comment]
I can't 100% reproduce it.
Will have logs tomorrow (after testing phase).

**Comment by scana** [comment]
@localhostEU So, did you manage to get those logs? ;)
I have the same problem, switching back to older version of Pushwoosh (i.e. older GCM implementation) works fine.
When I'm trying to send a push from control panel to a test device with a specific GCM token, it states that the push has been send successfully (so the token that I get is correct), but not delivered.

**Comment by localhostEU** [comment]
@scana We ended with implementing own microservice :)

**Comment by juliomarcos** [comment]
I'm also facing this bug

**Comment by shaders** [comment]
@juliomarcos this is strongly not recommended to register device immediately after unregistering it.
If you want to have opt-out strategy I recommend creating tag "opted-out" and using this as a filter when sending push.

**Comment by juliomarcos** [comment]
@shaders just what we did, what a coincidence. thanks.
