### ISSUE TITLE
Request client push or upstream push

### ISSUE THREAD

**Issue by akiwarheit** [Pushwoosh/pushwoosh-android-sdk#29]
Since your offering migration from Parse, I believe one feature Parse has is client or upstream push. I've scoured the documentation and I can't find a method that allows upstream push. [Parse: Sending Push from Android](https://parse.com/docs/android/guide#push-notifications-sending-pushes)

Specifically; [this](http://docs.pushwoosh.com/docs/createmessage) and [this](http://docs.pushwoosh.com/docs/createtargetedmessage) for Android would be the best. For the meantime; how do I send push notifications from an Android device to a target?

**Comment by shaders** [comment]
You can use createMessage function on the client side. Use your API key from https://cp.pushwoosh.com/v2/api_access  
Edit permission of the API token and allow your app to send client-side pushes via "Message sending will be available to subscribers of".

**Comment by akiwarheit** [comment]
> You can use createMessage function on the client side. Use your API key from https://cp.pushwoosh.com/v2/api_access

> Edit permission of the API token and allow your app to send client-side pushes via "Message sending will be available to subscribers of".

Thanks for the response. I get that I can use `createMessage` via the web API, but is there a method in the Android SDK that does this? Or do I have to make my own?

**Comment by shaders** [comment]
At the moment you have to make your own method. I'll ask our team to push this method in the SDK.

**Comment by akiwarheit** [comment]
@shaders thanks!

**Comment by viridanti** [comment]
The requested method has been implemented into our Android SDK. We have updated the documentation as well:

https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/Documentation/PushSender.md
https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/Documentation/PushMessage.md
