### ISSUE TITLE
Push custom handler

### ISSUE THREAD

**Issue by LinkOut** [Pushwoosh/pushwoosh-android-sdk#30]
I want to customize push behaviour if the application is opened or if its closed showing or not the notification.
So to do this, i have followed the tutorial on how to implement a Custom Push Broadcast Receiver, but when i receive a push, this is not handled by this Broadcast, even if i have set correctly the meta in the AndroidManifest.

I do not understand why this.

Thanks

**Comment by LinkOut** [comment]
Solved, Broadcast receiver actually handles the notif when user tapped on it, to handle the receive notif and the show/non show i used AbsNotificationFactory

**Comment by shaders** [comment]
:+1:
