### ISSUE TITLE
What is the need of Pushwoosh.Jar?

### ISSUE THREAD

**Issue by dkavithavijay** [Pushwoosh/pushwoosh-android-sdk#32]
Related to Android Mobile Application.
Developed with Eclipse IDE.

1. Once we create an Android App with some activities, we will get .apk after execution.
2. That .apk, uploaded in Google Play Store.
3. Later, I need to send push notifications to .apk which is installed in several mobile devices.
4. In this scenario, Pushwoosh should get only Google Project ID and then it can deliver push notifications to devices. is it not?

* Why we need to include pushwoosh.jar? Rolling back all AndroidManifest and MainActivity?
* Really I could not understand.
* I dont know, I may wrong. But still, Kindly clarify.

**Comment by wfhm** [comment]
Hello,

Pushwoosh SDK does not only get Project ID, it is responsible for **showing** and handling notifications on a device, collecting statistics, tracking device location, setting tag values and for a vast amount of other features, a full list of which you can find in our [Guides](http://docs.pushwoosh.com/docs/geozones).

**Comment by dkavithavijay** [comment]
No Sir. 

I could understand the use of Pushwoosh SDK.

But, My doubt regarding that is:

Example: Sample.apk
which has only one Main Activity: to display "Hello"

Then I uploaded that .apk to Google Play Store.
I have not included or implemented with pushwoosh sdk.

Now,

Can you tell me, How could i achieve push notifications through pushwoosh?

**Comment by dkavithavijay** [comment]
I need to make changes in same "Sample" android app with pushwoosh SDK?

Or

I need to create another Android App which includes project ID of "Sample" to send Push notification to "Sample"?

**Comment by wfhm** [comment]
> But, My doubt regarding that is:

> Example: Sample.apk
which has only one Main Activity: to display "Hello"

> Then I uploaded that .apk to Google Play Store.
I have not included or implemented with pushwoosh sdk.

> Now,

> Can you tell me, How could i achieve push notifications through pushwoosh?

IF the app has GCM API enabled everything you need to make your "Hello" app receive pushes is to include pushwoosh.jar to your libs, add push handling code to your app according to [our guide](http://docs.pushwoosh.com/docs/native-android-sdk), change IDs to match your app and [modify your AndroidManifest.xml](http://docs.pushwoosh.com/docs/androidmanifestxml-modifications)

**Comment by shaders** [comment]
Pushwoosh.jar is Pushwoosh SDK. It is required for the app to receive push notifications.
Please follow the integration guide on http://docs.pushwoosh.com/
The topic is closed.
