### ISSUE TITLE
Threading issues in Multi mode

### ISSUE THREAD

**Issue by kiruwka** [Pushwoosh/pushwoosh-android-sdk#33]
When enabling multiple notifications and when they are received at the same time, there are side-effects such as duplicate notification text, replacing messages, etc, related to thread racing conditions.

As each notification is handled in separate worker thread, you can fix it by making this code in `AbsNotificationFactory#notify` more thread-safe:

```
public final void notify(Context context, Bundle extra, PushData pushData) {
        ....
        this.mPushData = pushData; // <- mPushData keeps the value set by the last accessed thread
        
        ....
        if (!this.mPushData.isSilent()) {
            Notification notification = this.onGenerateNotification(this.mPushData); // <- just pass argument "pushData" instead so that notifications handled by different threads would always contain unique info
            this.generateNotification(notification, pushData.getMessageTag());
```

You can also make this method synchronized:

``` public static int getMessageId(Context context) ```

so that message id will be always unique, even when accessed by multiple threads at the same time. This will solve accidental "replacement" of notifications with same id that we had many times during our stress testing at Kapaza.

**Comment by shaders** [comment]
Should be fixed in https://github.com/Pushwoosh/pushwoosh-android-sdk/commit/f9b5d24fe5dd8c4cfa1a4aefb075ef4a31aeb5ec
