### ISSUE TITLE
Custom AbsNotificationFactory not working after restart

### ISSUE THREAD

**Issue by Sergios21** [Pushwoosh/pushwoosh-android-sdk#34]
Hi,
I have an issue with a custom AbsNotificationFactory that I've created. When I restart the device or when my application stays closed for a long time, then the notifications that I receive don't take into account any of the customizations that I make in my custom AbsNotificationFactory.

**Comment by shaders** [comment]
Hi,

Could you please make sure your custom factory has **public default constructor without any parameters**?

**Comment by t-kashima** [comment]
I also have same problem. When the application process does not start, InstantiationException error has occurred in the `factory = (AbsNotificationFactory)notificationFactoryClass.newInstance()`

**Comment by t-kashima** [comment]
Sorry, It wad solved by making a public default constructor.
