### ISSUE TITLE
Show notification in system bar/tray when app is in foreground

### ISSUE THREAD

**Issue by yuntao** [Pushwoosh/pushwoosh-android-sdk#35]
Is there a way to display the notification in the system bar/tray when app is running in the foreground? I noticed that there is a similar feature in the PhoneGap version using
`<meta-data android:name="PW_NO_BROADCAST_PUSH" android:value="true" />` 
(See https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/issues/103 and https://community.pushwoosh.com/questions/2287/notification-on-tray-even-when-app-is-in-foreground)

Would it be possible to bring this feature to the Pushwoosh Android SDK? Thanks!

**Comment by DimanAM** [comment]
BasePushMessageReceiver class is responsible for automatic push open in foreground. Just do not register it (or do not use it at all). In such case all notifications will appear in system tray and will be opened only when user clicks on them.

**Comment by yuntao** [comment]
Thanks for the pointer, @DimanAM. `BasePushMessageReceiver` registration is abstracted away when using the recommended [PushFragment](http://docs.pushwoosh.com/docs/android-sdk-fragments) integration. 

However, this led me to the correct configuration meta-data used by PushFragment.class and Config.class:
`<meta-data android:name="PW_BROADCAST_PUSH" android:value="false" />`
:)
