### ISSUE TITLE
DeadObjectExceptions for 9300 and 9305 Samsung S3 on Android 4.3

### ISSUE THREAD

**Issue by n-belokopytov** [Pushwoosh/pushwoosh-android-sdk#37]
Hey guys, we've recently started to get a lot of DeadObjectExceptions for 9300 and 9305 Samsung S3 on Android 4.3. The stack looks like that basically and I cannot reproduce it with an emulator

Config.java com.pushwoosh.internal.utils.Config <init> 28 Config.java com.pushwoosh.internal.utils.Config getInstance 59 PushEventsTransmitter.java com.pushwoosh.internal.PushEventsTransmitter getUseBroadcast 29 PushEventsTransmitter.java com.pushwoosh.internal.PushEventsTransmitter onRegisterError 83 DeviceRegistrar.java com.pushwoosh.internal.registrar.DeviceRegistrar$1InnerRegistrationListener onError 52 PushRequest.java com.pushwoosh.internal.request.PushRequest setProcessed 73 RequestManager.java com.pushwoosh.internal.request.RequestManager$1$1 run 167

or

Config.java com.pushwoosh.internal.utils.Config <init> 28 Config.java com.pushwoosh.internal.utils.Config getInstance 59 PushEventsTransmitter.java com.pushwoosh.internal.PushEventsTransmitter getUseBroadcast 29 PushEventsTransmitter.java com.pushwoosh.internal.PushEventsTransmitter onRegisterError 83 GCMRegistrationService.java com.pushwoosh.GCMRegistrationService register 63 GCMRegistrationService.java com.pushwoosh.GCMRegistrationService onHandleIntent 106

Do you have any idea on what's happening? We are using PushWoosh 3.5.3, here's my init code - it's in a singleton.

```
   try {
        this.context = context;
        PushManager.initializePushManager(context, gygConfig.getPushWooshKey(), gygConfig.getGCMNumber());
        pushManager = PushManager.getInstance(context);
        pushManager.onStartup(context);
        pushManager.registerForPushNotifications();
        pushManager.setNotificationFactory(new PushFactory());
    } catch (Exception e) {
        Log.e(TAG, "Failed to track to PushWoosh", e);
    }
```

**Comment by DimanAM** [comment]
Do you call Pushwoosh SDK methods in a separate process? Can you please share your AndroidManifest.xml or apk build?

**Comment by n-belokopytov** [comment]
@DimanAM 

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.getyourguide.android">

    
    <uses-feature
        android:name="android.hardware.camera"
        android:required="true" />
    <uses-feature
        android:name="android.hardware.camera.autofocus"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera.flash"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.telephony"
        android:required="false" />
    <uses-feature
        android:glEsVersion="0x00020000"
        android:required="true" />

    
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

    
    <uses-permission android:name="android.permission.CAMERA" />

    
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="${applicationId}.permission.MAPS_RECEIVE" />

    
    <uses-permission
        android:name="android.permission.VIBRATE"
        tools:node="remove" />
    <uses-permission
        android:name="android.permission.READ_PHONE_STATE"
        tools:node="remove" />

    <permission
        android:name="${applicationId}.permission.MAPS_RECEIVE"
        android:protectionLevel="signature" />

    <uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />

    <permission
        android:name="${applicationId}.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />

    <supports-screens
        android:largeScreens="true"
        android:normalScreens="true"
        android:smallScreens="true"
        android:xlargeScreens="true" />

    <application
        android:name=".GYGApplication"
        android:allowBackup="true"
        android:backupAgent=".backup.GYGBackup"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:logo="@drawable/ic_actionbar_icon"
        android:theme="@style/ThemeNoActionBar.GYG">

        
        
        <receiver android:name=".receivers.BootCompletedReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

        
        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>

        <service
            android:name="com.pushwoosh.GCMListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
            </intent-filter>
        </service>

        <service
            android:name="com.pushwoosh.GCMInstanceIDListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.gms.iid.InstanceID"/>
            </intent-filter>
        </service>

        <service
            android:name="com.pushwoosh.GCMRegistrationService"
            android:exported="false">
        </service>


        <receiver android:name=".receivers.PushWooshReceiver" />
        <meta-data android:name="PW_NOTIFICATION_RECEIVER" android:value=".receivers.PushWooshReceiver"/>

        
        <service android:name="com.pushwoosh.location.GeoLocationService" />

        
        <receiver
            android:name="com.adjust.sdk.AdjustReferrerReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>

        
        <receiver
            android:name="com.mixpanel.android.mpmetrics.GCMReceiver"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>

        
        <activity
            android:name=".activities.AppIntroActivity"
            android:screenOrientation="portrait"
            android:theme="@style/ThemeNoActionBar.GYG.Fullscreen.Black">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <activity
            android:name=".activities.DeepLinkDispatcherActivity"
            android:screenOrientation="portrait">

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="home"
                    android:scheme="gyg" />
                <data
                    android:host=""
                    android:scheme="gyg" />
                <data
                    android:host="tickets"
                    android:scheme="gyg" />
                <data
                    android:host="tours"
                    android:scheme="gyg" />
                <data
                    android:host="search"
                    android:scheme="gyg" />
                <data
                    android:host="login"
                    android:scheme="gyg" />
                <data
                    android:host="review"
                    android:scheme="gyg" />
                <data
                    android:host="discovery"
                    android:scheme="gyg" />
            </intent-filter>

            <intent-filter
                android:autoVerify="true"
                tools:ignore="UnusedAttribute">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="www.getyourguide.com"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.dk"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.de"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.at"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.ch"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.co.uk"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.es"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.fr"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.it"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.nl"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.no"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.pt"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.com.br"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.fi"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.se"
                    android:scheme="https" />
                <data
                    android:host="www.getyourguide.com.tr"
                    android:scheme="https" />
            </intent-filter>
        </activity>

        <activity android:name=".activities.HomeActivity" />
        <activity android:name=".activities.SearchResultActivity">
            <intent-filter>
                <action android:name="android.intent.action.SEARCH" />
            </intent-filter>
        </activity>
        <activity android:name=".activities.FilterActivity" />
        <activity android:name=".activities.Web2AppLandingActivity" />
        <activity android:name=".activities.TourDetailActivity" />
        <activity android:name=".activities.TourDetailTabActivity" />
        <activity
            android:name=".activities.WebviewActivity"
            android:configChanges="orientation|keyboardHidden" />
        <activity android:name=".activities.BookTourActivity" />
        <activity android:name=".activities.MeetingPointActivity" />
        <activity
            android:name=".activities.TicketDetailActivity"
            android:screenOrientation="sensorPortrait" />
        <activity android:name=".activities.AdditionalBookingInfoActivity" />
        <activity android:name=".activities.AboutActivity" />
        <activity android:name=".activities.HelpActivity" />
        <activity android:name=".activities.RedeemCouponActivity" />
        <activity android:name=".activities.SearchActivity" />
        <activity
            android:name=".activities.POIDetailActivity"
            android:theme="@style/ThemeNoActionBar.GYG.Light" />
        <activity android:name=".activities.SignInSignUpActivity" />
        <activity android:name=".activities.UpdateAppActivity" />
        <activity
            android:name=".activities.WebPaymentDetailActivity"
            android:configChanges="orientation|keyboardHidden|screenSize" />
        <activity android:name="com.mixpanel.android.surveys.SurveyActivity" />

        <activity
            android:name="io.card.payment.CardIOActivity"
            android:configChanges="keyboardHidden|orientation"
            android:hardwareAccelerated="true" />
        <activity
            android:name="io.card.payment.DataEntryActivity"
            android:screenOrientation="portrait" />

        
        <activity android:name="com.pushwoosh.richpages.RichPageActivity" />
        <activity android:name="com.pushwoosh.MessageActivity" />
        <activity android:name="com.pushwoosh.PushHandlerActivity" />

        
        <service android:name=".real_services.LoadTourService" />
        <service android:name=".real_services.LoadTourOptionsService" />
        <service android:name=".real_services.GeofenceTransitionsIntentService" />

        
        
        <activity
            android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name"
            android:theme="@android:style/Theme.Translucent.NoTitleBar" />
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id_default" />

        
        <meta-data
            android:name="com.google.android.maps.v2.API_KEY"
            android:value="@string/google_map_key" />
        <meta-data
            android:name="APP_NAME"
            android:value="${applicationId}" />
        <meta-data
            android:name="com.google.android.backup.api_key"
            android:value="@string/backup_api_key" />
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
    </application>
</manifest>
`

Here's my manifest. What do you mean by a separate process? A Service or another app? No. Different threads? Maybe.

**Comment by n-belokopytov** [comment]
@DimanAM for an APK you can just download GetYourGuide app from the PlayStore.

**Comment by DimanAM** [comment]
This is very strange **DeadObjectException** usually occurs when one process tries to access an object managed by another process that has been terminated. However it seems your application indeed uses only one process.
I have made a workaround for this in 4.3.3 release.

BTW how often does this issue occur?

**Comment by n-belokopytov** [comment]
@DimanAM yeah, that's what I thought as well. This issue occurs only on 4.3 platform on Galaxy S3s, we get it 5-6 times a day out of 20 daily installs for these devices. It has started to occur approximately since last Friday 24th of June.

**Comment by n-belokopytov** [comment]
@DimanAM the new version 4.3.3 is much more stable, thank you, however there are still 3 crashes in 3 days with that stacktrace. Same as before - it's only on Samsung 9300 and 4.3 system.

Exception Backtrace:
1	android.app.ApplicationPackageManager.getApplicationInfo	ApplicationPackageManager.java, line 245
2	com.pushwoosh.internal.utils.a.<init>	Unknown Source
3	com.pushwoosh.internal.utils.a.a	Unknown Source
4	com.pushwoosh.internal.a.a	Unknown Source
5	com.pushwoosh.internal.a.a	Unknown Source
6	com.pushwoosh.internal.a.a$a.a	Unknown Source
7	com.pushwoosh.internal.b.g.setProcessed	Unknown Source
8	com.pushwoosh.internal.b.k$1$1.run	Unknown Source
9	android.os.Handler.handleCallback	Handler.java, line 730
10	android.os.Handler.dispatchMessage	Handler.java, line 92
11	android.os.Looper.loop	Looper.java, line 176
12	android.app.ActivityThread.main	ActivityThread.java, line 5419
13	java.lang.reflect.Method.invokeNative	Native Method
14	java.lang.reflect.Method.invoke	Method.java, line 525
15	com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run	ZygoteInit.java, line 1046
16	com.android.internal.os.ZygoteInit.main	ZygoteInit.java, line 862
17	dalvik.system.NativeStart.main	Native Method
Caused by: android.os.DeadObjectException
1	android.os.BinderProxy.transact	Native Method
2	android.content.pm.IPackageManager$Stub$Proxy.getApplicationInfo	IPackageManager.java, line 1816
3	android.app.ApplicationPackageManager.getApplicationInfo	ApplicationPackageManager.java, line 240
... 16 more
