### ISSUE TITLE
error missing instanceid

### ISSUE THREAD

**Issue by iccunha** [Pushwoosh/pushwoosh-android-sdk#38]
please, help
[Screenshot error](http://prntscr.com/bo669q)

**Comment by DimanAM** [comment]
Make sure you have Google Play Sevcices installed on your device or emulator.

https://developers.google.com/android/guides/setup

To test your app when using the Google Play services SDK, you must use either:

* A compatible Android device that runs Android 2.3 or higher and includes Google Play Store.
* The Android emulator with an AVD that runs the Google APIs platform based on Android 4.2.2 or higher.
