### ISSUE TITLE
To many permissions needed

### ISSUE THREAD

**Issue by PiotrWpl** [Pushwoosh/pushwoosh-android-sdk#39]
Hi!

After 4.3.0 version Pushwoosh SDK automaticaly added two new permissions:

- android.permission.READ_PHONE_STATE
- android.permission.GET_ACCOUNTS

Why?
As I remember well, they were optional before. Do we really need them? Our application got some 1 star rates in Google Play Store because they appeared after app update.

**Comment by PiotrWpl** [comment]
I have removed them thanks to this article -> https://commonsware.com/blog/2015/06/25/hey-where-did-these-permissions-come-from.html

Is it safe? Or maybe something bad can happen because of that?

**Comment by shaders** [comment]
It should be safe. You can find more information on SDK permissions here:
http://docs.pushwoosh.com/docs/android-faq#what-permissions-are-necessary-and-what-are-option

**Comment by PiotrWpl** [comment]
Thx. There should be some info about that in changelog. Some users are really sensitive about permissions. And now we need to ask them about change their rating.

**Comment by shaders** [comment]
We are considering to remove this permissions from the SDK in the next update.
