### ISSUE TITLE
Where has the Android source code gone!?

### ISSUE THREAD

**Issue by rgozim** [Pushwoosh/pushwoosh-android-sdk#4]
What has happened to the Android SDK source code?

It was here last year and now it's gone. It's been replaced by jar, which is nice for some users, but not ideal for everyone else.

**Comment by cgwyllie** [comment]
@shaders Is this likely to come back any time soon?

**Comment by shaders** [comment]
Could you let me know why would you need this?

**Comment by cgwyllie** [comment]
@shaders It can be useful for step debugging, understanding event flow, and it would allow community contributions :)

**Comment by shaders** [comment]
This is possible but not at the very moment.
