### ISSUE TITLE
No details in VERSION.md

### ISSUE THREAD

**Issue by PiotrWpl** [Pushwoosh/pushwoosh-android-sdk#42]
Hi,

in my opinion changelog in VERSION.md:
> Support getLaunchNotification with custom push receiver

is not enough. It will be much better with more details like: link to the documentation and sample use case.

When I see:

> getLaunchNotification with custom push receiver

or

> Remote pushwoosh commands

I'm not sure if i need or not ;)

Thanks in advance.
Greetings.

**Comment by shaders** [comment]
Thank you for the feedback!
