### ISSUE TITLE
How to turn on/off push notification?

### ISSUE THREAD

**Issue by kanvuduc** [Pushwoosh/pushwoosh-android-sdk#43]
I tried to turn on/off push notification from a Setting menu.

BUT it doesn't work.

Because we always run PushFragment.init on the main activity which always register for push notification.

If I don't call that, but PushFragment.getFragment, then call register, it failed with NullPointerException.

Plz advice.

**Comment by DimanAM** [comment]
Both `PushFragment.init` and `PushFragment.getPushFragment` will automatically register for push notifications when Fragment is created. You need to call register only if Fragment already exists:

```java
PushFragment fragment = PushFragment.getPushFragment(yourActivity);
if (PushFragment.hasFragment(yourActivity)) {
     fragment.register();
}
```
Enabling/disabling notification alerts can be also done using [NotificationFactory](http://docs.pushwoosh.com/docs/androidmanifestxml-modifications#customizing-push-notifications). If you return `null` in `onGenerateNotification(PushData pushData)` no notification will be generated.
