### ISSUE TITLE
JSONException when parsing server responses

### ISSUE THREAD

**Issue by vicpinm** [Pushwoosh/pushwoosh-android-sdk#46]
Since today, I'm getting strange exceptions when my app is performing some actions with the sdk.

For example, I'm getting this exception:

          x
          |     Pushwoosh request:
          | Url: https://B65C1-67A8B.api.pushwoosh.com/json/1.3/setTags
          | Payload: {"request":{"tags":{"msisdn":    ["722505881","722500437"]},"v":"4.8.4","application":"53268-AB926","hwid":"65d5d76e02c11164","device_type":3,"userId":"65d5d76e02c11164"}}
          | Response: {"status_code":200,"status_message":"OK","response":{"skipped":{}}}
          x
     [RequestManager] setTags response success
     [RequestManager] ERROR: Value {} at skipped of type org.json.JSONObject cannot be converted to   JSONArray. Response = {"response":{"skipped":{}},"status_code":200,"status_message":"OK"}
           org.json.JSONException: Value {} at skipped of type org.json.JSONObject cannot be converted to   JSONArray at org.json.JSON.typeMismatch(JSON.java:100)
           at org.json.JSONObject.getJSONArray(JSONObject.java:552)
           at com.pushwoosh.internal.b.o.parseResponse(Unknown Source)
           at com.pushwoosh.internal.b.l.a(Unknown Source)
           at com.pushwoosh.internal.b.l$1.run(Unknown Source)

**Comment by shaders** [comment]
Fixed.
