### ISSUE TITLE
Rich media page Forbidden 403

### ISSUE THREAD

**Issue by apo1981** [Pushwoosh/pushwoosh-android-sdk#47]
Hi

I have updated to new version of sdk (4.9.0) because the pushwoosh library I was using (old one - jar version) does not receive any push notification anymore (compatibility issues????)

So, I have been forced to update to the latest version, and now I receive normal push notifications where the action is open the app.

However, when a push notification is sent with a rich media page, and the notification is open, the rich media page is not open and the 403 Forbidden message is show on the screen. This does not happen with the old sdk version I have integrated.

Why is this happening?

Thank you

**Comment by shaders** [comment]
Can you tell me the message ID or App Code so I can take a look in the system what was going on?

**Comment by apo1981** [comment]
Thks @shaders, this is the app code id = B713A-E3EF8

**Comment by apo1981** [comment]
Let me add the following information. I have tested with different version of the library
- v4.8.2: push notification is received and rich-media CORRECTLY open
- v4.8.3 (API change): push notification is received, but rich-media NOT correctly open (403 Forbidden)
- 4.9.0 (latest one): same as v4.8.3

**Comment by DimanAM** [comment]
There should be nothing related to rich media in 4.8.3 release. 
Does this problem appear on any/specific device?
Does the problem persist if you clear application data?
Could you please attach device logs when push notification is received and opened?

**Comment by apo1981** [comment]
@DimanAM 
Does this problem appear on any/specific device? Any device
Does the problem persist if you clear application data? We have uninstall and install the app again, and the issue persist

**Comment by shaders** [comment]
I've got this reproduced. Should be fixed soon, I'll keep you posted.

**Comment by apo1981** [comment]
Thank you @shaders 
I will integrate v4.8.2 atm, and will wait for your fixed

**Comment by shaders** [comment]
Fixed in https://github.com/Pushwoosh/pushwoosh-android-sdk/commit/b115a2d3376a5bef97c538590aec396222d127f6
