### ISSUE TITLE
How to stack new notifications rather then making them override previous one? 

### ISSUE THREAD

**Issue by katepratik** [Pushwoosh/pushwoosh-android-sdk#49]
Currently all new notifications replaces the previous old once that user has not seen. User is not able to see his/her old notification in list into his notification panel. What the work around?

**Comment by DimanAM** [comment]
You should use [setMultiNotificationMode](https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/Documentation/PushManager.md#setmultinotificationmode) to display all notifications separetely.

**Comment by katepratik** [comment]
Oh! I missed that thing thanks :) 
But i still have one issue, i need to group some notifications based on their type and show them as one single notification. While others can be seen as Multi Notification.

**Comment by DimanAM** [comment]
You will need to implement [custom notification factory](http://docs.pushwoosh.com/docs/androidmanifestxml-modifications#customizing-push-notifications) to achieve that. Here is an example of how it could be done: https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/Samples/Android-Advanced/app/src/main/java/com/pushwoosh/sample/inbox/InboxNotificationFactory.java.

Key point here is that you need to fire Inbox notification manually
https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/Samples/Android-Advanced/app/src/main/java/com/pushwoosh/sample/inbox/InboxNotificationFactory.java#L56 to be able to update the existing notification.

**Comment by katepratik** [comment]
Oh! Cool, thanks a lot @DimanAM

**Comment by alexakasanjeev** [comment]
Hi, how to slove this problem, SDK of pushwoosh has changed above method do not work

If I generate notification manually using notify method, then there is a problem, if notification is clicked it won't update the pushwoosh, so the statistics that show how many notification is opened won't work
