### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by LupoBianco** [Pushwoosh/pushwoosh-android-sdk#52]
same as [https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/issues/233](url)

`Fatal Exception: java.lang.RuntimeException: Unable to instantiate receiver com.pushwoosh.MessageAlertReceiver: java.lang.ClassNotFoundException: Didn't find class "com.pushwoosh.MessageAlertReceiver" on path`

on Android 4.3.1 (Motorola Defy Mini XT320)

**Comment by wfhm** [comment]
Hi,

We are on it. We will update this thread as soon as we fix this issue.

**Comment by DimanAM** [comment]
Should be fixed in 4.12.0

**Comment by LupoBianco** [comment]
Yeahh! Thanks!
