### ISSUE TITLE
Migration to Firebase SDK

### ISSUE THREAD

**Issue by leandro-dev** [Pushwoosh/pushwoosh-android-sdk#53]
Remove the dependency of the library _**com.google.android.gms:play-services-gcm**_ and start using the Firebase library instead: _**com.google.firebase:firebase-messaging**_

Firebase Cloud Messaging (FCM) is the new version of GCM. For more information, access https://developers.google.com/cloud-messaging/faq

**Comment by wfhm** [comment]
@leandro-dev 

FCM is supported since 5.1.0 release.
