### ISSUE TITLE
setting app badge count no longer working on samsung S7 on android 7

### ISSUE THREAD

**Issue by mccraigmccraig** [Pushwoosh/pushwoosh-android-sdk#55]
i'm using the pushwoosh-android-sdk 4.12.2 via the pushwoosh-cordova-plugin 6.5.3

setting app icon badge counts is no longer working on my samsung S7 on android 7

some detective work leads me to the probably cause being this recent ShortcutBadger bug - https://github.com/leolin310148/ShortcutBadger/issues/199

**Comment by firodj** [comment]
I've also found same problem and it seems because of old `ShortcutBadger` version. Is there any workaround? @DimanAM 
thanks.

**Comment by shaders** [comment]
checking this.

**Comment by mccraigmccraig** [comment]
any update on this issue ? samsungs are popular, and my samsung-based users are giving me grief about this

**Comment by shaders** [comment]
Fixed in 5.0.2 https://github.com/Pushwoosh/pushwoosh-android-sdk/releases/tag/5.0.2
