### ISSUE TITLE
How to pass Push token to Pushwoosh if handled manually?

### ISSUE THREAD

**Issue by salah-ghanim** [Pushwoosh/pushwoosh-android-sdk#58]
According to the documentations concerning using multiple push libraries:

> Do the same for InstanceIdListenerService to listen correctly for the push token changes. We'll leave this for homework. :)

http://docs.pushwoosh.com/docs/android-faq

Yet I can't find any public API I can use to provide said token once parsed by my receiver. 

On the other hand intercom seems to have a pretty clean way to document and consume it.
https://developers.intercom.com/docs/android-gcm-push-notifications

So is there any api for passing the token? or I should count on Pushwoosh for now to receive the token and register a receiver for the token update? seems like registering for a callback can be a way to do it.

**Comment by wfhm** [comment]
Hi,

At the moment there is no method to pass a token to Pushwoosh InstanceIdListenerService. On the other hand, Pushwoosh SDK can receive a token from GCM and pass it to Intercom as described in their guide:

https://developers.intercom.com/docs/android-gcm-push-notifications#section-step-7-using-intercom-with-other-gcm-setups-optional

**Comment by salah-ghanim** [comment]
hmm, even in that case it seems like the only way to get the latest token would be by calling

Pushwoosh.registerForPushNotifications() and use the listener to get the latest token and send it every time to my provider (intercom) since I can't know if I have the token changed at some point.

I'm rolling back our Pushwoosh SDK to 4 since it seems like there is a broadcast receiver for push token updates which make more sense. 


--

**Comment by wfhm** [comment]
Hi,

You can subscribe for push token change event:

```
Subscription<RegistrationSuccessEvent> registrationSuccessEventSubscription = EventBus.subscribe(RegistrationSuccessEvent.class, new EventListener<RegistrationSuccessEvent>() {
@Override
public void onReceive(RegistrationSuccessEvent event) {
String token = event.getData();
//do what you want with token
}
});
```

Then, if a token changes, `registerForPushNotifications` is called to send a new token to Pushwoosh. You can obtain a new token from a callback if needed and pass it to Intercom listener.

You can always unsubscribe from this event with 

```
registrationSuccessEventSubscription.unsubscribe();
```
