### ISSUE TITLE
Compatibility with Android O (8.0)

### ISSUE THREAD

**Issue by n-belokopytov** [Pushwoosh/pushwoosh-android-sdk#59]
We are having some Googlers test our app on Pixel2 with Android O and it appears that your SDK is not O-ready. We get the following error.

java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.getyourguide.android/com.pushwoosh.inapp.InAppRetrieverService (has extras) }: app is in background uid UidRecord

Please refer to this page for the explanation. https://developer.android.com/preview/features/background.html#services

**Comment by n-belokopytov** [comment]
I believe that it would be easy to refactor by using this https://developer.android.com/reference/android/support/v4/app/JobIntentService.html

**Comment by shaders** [comment]
Hi, Android O support is currently in progress. Should be released soon. Will keep you posted.

**Comment by n-belokopytov** [comment]
@shaders hello, please give us an ETA. We get about 200 issues because of that each day and would like to make a decision.

**Comment by shaders** [comment]
Release should be tomorrow or the day after.

**Comment by shaders** [comment]
https://github.com/Pushwoosh/pushwoosh-android-sdk/releases/tag/5.0.3
