### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by ghost** [Pushwoosh/pushwoosh-android-sdk#6]
Could you please make your library available through gradle?

**Comment by gregorko** [comment]
Maybe by either providing your own maven repository or by pushing the jar to a public maven repository.
Then it would be possible to integrate the jar by specifying a dependency in the gradle file like for example:
``compile 'com.pushwoosh:pushwoosh:2.9.4' ``

**Comment by shaders** [comment]
By the way this has been done. See step 1 at:
https://www.pushwoosh.com/programming-push-notification/android/native-android-sdk-integration/

compile 'com.pushwoosh:pushwoosh:+'
