### ISSUE TITLE
Pushwoosh.getInstance().getTags() after sendTags() doesn't seem to work

### ISSUE THREAD

**Issue by 089apps** [Pushwoosh/pushwoosh-android-sdk#60]
Based on your Android-advanced sample I saved a listTag "MY_CHANNELS" = ["1","2"], which appears while debugging `tags = tagsPushwoosh.getInstance().getTags()`.
But I wonder why `tags.getList("MY_CHANNELS")` always returns `null`
`tags.getList("MY_CHANNELS") = null`
`result.getData().getList("MY_CHANNELS") = null`

Tried with 5.0.1 and 5.0.2, tried with `intTags` and `listTags`.
Would be happy if you'd check this and complement the examples. thx so much

`Pushwoosh.getInstance().getTags((result) -> {
            if (result.isSuccess()) {
                // tags sucessfully received
                int listTag = result.getData().getList("MY_CHANNELS");
                Log.d(LTAG, "MY_CHANNELS: " + listTag);
            }
            else {
                // failed to receive tags
            }
        });`

These are every tags I receive:
_tags = {TagsBundle@4769} 
 a = {HashMap@4793}  size = 6
  0 = {HashMap$HashMapEntry@4797} "Last Application Open" -> "1502928000"
  1 = {HashMap$HashMapEntry@4798} "First Install" -> "1502409600"
  2 = {HashMap$HashMapEntry@4799} "Application Version" -> "1.0.0.0"
  3 = {HashMap$HashMapEntry@4800} "City" -> "XXXX"
  4 = {HashMap$HashMapEntry@4801} "Country" -> "XXXX"
  5 = {HashMap$HashMapEntry@4802} "Language" -> "XXXX"_
  5 = {HashMap$HashMapEntry@4802} "MY_CHANNELS" -> ["1","2"]

**Comment by wfhm** [comment]
Got it reproduced. The fix will be rolled out with the next release. 

Meanwhile you can use the workaround below to get a value of a list Tag:

```
Pushwoosh.getInstance().getTags(new Callback<TagsBundle, GetTagsException>() {
	@Override
	public void process(@NonNull final Result<TagsBundle, GetTagsException> result) {
		if (result.isSuccess()) {
			JSONArray myChannels = result.getData().toJson().get("MY_CHANNELS");
		}
	}
});
```
