### ISSUE TITLE
Unable to clear all scheduled local notifications

### ISSUE THREAD

**Issue by n-belokopytov** [Pushwoosh/pushwoosh-android-sdk#61]
Previously we've used the method to clear all local scheduled notifications, however now it's only possibly to do so by ID. We are doing that, however we started to get the following error on 6.0.1 androids and higher:

java.lang.SecurityException: !@Too many alarms (500) registered from pid 7173 uid 10043
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.os.Parcel.readException(Parcel.java:1573)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:217)
	at android.app.AlarmManager.setImpl(AlarmManager.java:484)
	at android.app.AlarmManager.set(AlarmManager.java:260)
	at com.pushwoosh.notification.LocalNotificationReceiver.scheduleNotification(Unknown Source)
	at com.pushwoosh.notification.e.f(Unknown Source)
	at com.pushwoosh.c.a(Unknown Source)
	at com.pushwoosh.c.a(Unknown Source)
	at com.pushwoosh.f.onReceive(Unknown Source)
	at com.pushwoosh.internal.event.EventBus.b(Unknown Source)
	at com.pushwoosh.internal.event.EventBus.c(Unknown Source)
	at com.pushwoosh.internal.event.EventBus.a(Unknown Source)
	at com.pushwoosh.internal.event.c.run(Unknown Source)

It seems like the scheduleNotification method is not even called by our code in that case. We have already gathered about 200 hundred crashes for 3 days. Thank you.

**Comment by wfhm** [comment]
Checking this.

**Comment by wfhm** [comment]
Got it reproduced.

If deleting local notifications correctly, the crash might be avoided. To cancel all Pushwoosh-related local notifications, use:

```
LocalNotificationReceiver.cancelAll();
```

Please note that other alarms in your app that are not managed by Pushwoosh SDK will not be canceled.

**Comment by n-belokopytov** [comment]
@wfhm thank you for clearing that up! It was not apparent for me how to do that, since the scheduling of notifications and deleting them one by one happens on Pushwoosh's instance. FYI I think that the documentation could be improved if this class is mentioned explicitly. I was not able to find it here 
https://rawgit.com/Pushwoosh/pushwoosh-android-sdk/master/Documentation/com/pushwoosh/notification/package-summary.html

**Comment by n-belokopytov** [comment]
@wfhm FYI we are still receiving same crash reports after scheduling the notification like the following:

` LocalNotification localNotification = new LocalNotification.Builder().setMessage(notification.getText()).setExtras(bundle).setDelay(seconds).build();
                    ids.add(String.valueOf(Pushwoosh.getInstance().scheduleLocalNotification(localNotification).getRequestId()));
`

and then clear them like
`LocalNotificationReceiver.cancelAll();`

Should we use LocalNotificationReceiver.scheduleNotification(bundle, seconds)) instead of the getInstance() one? If so, what would be the bundle parameter for Text Message in it?

**Comment by wfhm** [comment]
@n-belokopytov 

> Should we use LocalNotificationReceiver.scheduleNotification(bundle, seconds)) instead of the getInstance() one? If so, what would be the bundle parameter for Text Message in it?

You can make sure that all Pushwoosh-generated alarms are canceled after calling `LocalNotificationReceiver.cancelAll();`. You should add a few local notifications, then call **adb shell dumpsys alarm** in terminal and check whether `LocalNotificationReceiver.cancelAll();` cancels it. Please share a result of **adb** with us.

Also, do you use any alarms in your app created without using Pushwoosh SDK?

**Comment by n-belokopytov** [comment]
@wfhm we are not using any other alarms in our app apart from the ones created by Pushwoosh SDK. Today we have checked our internal event tracking system and found out that even when using your suggested "cancelAll" method, some users receive 700 Local Push Notifications. It leads us to believe that it is somehow related with the way we are scheduling them. Please provide us the bundle parameter name for Text Message so we could test it as well.

**Comment by wfhm** [comment]
@n-belokopytov Sorry for the delay!

The name of this bundle parameter is "title".

**Comment by gholz** [comment]
Upon further investigation we found out it might be a common issue with some samsung devices, Firebase had a similar problem not to long ago as you can see here:
https://groups.google.com/forum/#!topic/firebase-talk/Q_zycHnTGu0

**Comment by n-belokopytov** [comment]
@wfhm thank you very much. Could you confirm that you are using the FCM version above 10.x that was mentioned as a fix in https://groups.google.com/forum/#!topic/firebase-talk/Q_zycHnTGu0
?

**Comment by wfhm** [comment]
@n-belokopytov FCM support will be added in the upcoming 5.1.0 release. The latest version of FCM will be used.

**Comment by wfhm** [comment]
@n-belokopytov 5.1.0 release is rolled out.

**Comment by n-belokopytov** [comment]
@wfhm still seeing problems on 5.1.1, with FCM 11.4.2

Android OS > 6.0, Samsung devices

Exception Backtrace:
--
1 | android.os.Parcel.readException | Parcel.java, line 1620
2 | android.os.Parcel.readException | Parcel.java, line 1573
3 | android.app.IAlarmManager$Stub$Proxy.set | IAlarmManager.java, line 217
4 | android.app.AlarmManager.setImpl | AlarmManager.java, line 484
5 | android.app.AlarmManager.set | AlarmManager.java, line 260
6 | com.pushwoosh.notification.LocalNotificationReceiver.scheduleNotification | Unknown Source
7 | com.pushwoosh.notification.e.f | Unknown Source
8 | com.pushwoosh.g.a | Unknown Source
9 | com.pushwoosh.g.a | Unknown Source
10 | com.pushwoosh.j.onReceive | Unknown Source
11 | com.pushwoosh.internal.event.EventBus.b | Unknown Source
12 | com.pushwoosh.internal.event.EventBus.c | Unknown Source
13 | com.pushwoosh.internal.event.EventBus.a | Unknown Source
14 | com.pushwoosh.internal.event.c.run | Unknown Source
15 | android.os.Handler.handleCallback | Handler.java, line 739

16 | android.os.Handler.dispatchMessage | Handler.java, line 95
17 | android.os.Looper.loop | Looper.java, line 158
18 | android.app.ActivityThread.main | ActivityThread.java, line 7230
19 | java.lang.reflect.Method.invoke | Native Method
20 | com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run | ZygoteInit.java, line 1230
21 | com.android.internal.os.ZygoteInit.main | ZygoteInit.java, line 1120

**Comment by wfhm** [comment]
@n-belokopytov thanks for the details. The 5.1.0 version only introduced FCM support, yet a fix was not applied. It will be rolled out with the next release.

**Comment by wfhm** [comment]
@n-belokopytov fixed in 5.4.0.
