### ISSUE TITLE
Android O IllegalStateException in PushGcmIntentService

### ISSUE THREAD

**Issue by aradosz** [Pushwoosh/pushwoosh-android-sdk#64]
`09-01 12:21:17.013 27032-27032/pl.onet.onethd.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: pl.onet.onethd.debug, PID: 27032
                                                                      java.lang.RuntimeException: Unable to start receiver com.google.android.gms.gcm.GcmReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010 pkg=pl.onet.onethd.debug cmp=pl.onet.onethd.debug/com.pushwoosh.PushGcmIntentService (has extras) }: app is in background uid UidRecord{6355de9 u0a115 TRNB idle procs:2 seq(0,0,0)}
`

Looks like this crash is similar to https://github.com/Pushwoosh/pushwoosh-android-sdk/issues/59

In documentation is no info about using com.google.android.gms:play-services-gcm:11.+

**Comment by wfhm** [comment]
Hi,

Could you please specify which particular device models are affected by the issue and provide a full stack trace?

**Comment by wfhm** [comment]
@aradosz any news?

**Comment by aradosz** [comment]
Now is ok, but I was testing on gcm 10,  when I add dependencies for gcm 11 start working properly

**Comment by wfhm** [comment]
Thank you for your feedback! Readme has been updated.
