### ISSUE TITLE
Custom tags in Android SDK 5.0

### ISSUE THREAD

**Issue by EstebanC02** [Pushwoosh/pushwoosh-android-sdk#68]
Hi, I'm reading the documentation for the migration to SDK 5.0, but I don't see support for Custom Tags in Java code, I only see the implementation with JavaScript, the code I had before no longer works:

`PushManager. sendTags (getApplicationContext (), myMap, null);`

> Javascript

```
//sets a string tag “username” with value “john” and integer tag “deviceId” with value 10
pushNotification.setTags({username:"john", deviceId:10},
    function(status) {
        console.warn('setTags success');
    },
    function(status) {
        console.warn('setTags failed');
    }
);

//sets a list tag "MyTag" with values "hello", "world"
pushNotification.setTags({"MyTag":["hello", "world"]});
```

How do I make it work?

**Comment by wfhm** [comment]
Hi, 

Please check our updated [Sample app](https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/Samples/Android-Advanced/app/src/main/java/com/pushwoosh/sample/PushwooshSampleApp.java#L29):

```
Pushwoosh.getInstance().sendTags(Tags.intTag("fav_number", 42));
```

To set a custom tag value you can use [sendTags](https://rawgit.com/Pushwoosh/pushwoosh-android-sdk/master/Documentation/com/pushwoosh/Pushwoosh.html#sendTags-com.pushwoosh.tags.TagsBundle-) method with [TagsBundle](https://rawgit.com/Pushwoosh/pushwoosh-android-sdk/master/Documentation/com/pushwoosh/tags/TagsBundle.html) as a parameter. 

You can also use [Tags](https://rawgit.com/Pushwoosh/pushwoosh-android-sdk/master/Documentation/com/pushwoosh/tags/Tags.html) class methods for setting values for single Tags of different types.
