### ISSUE TITLE
Duplicate Location Services Message

### ISSUE THREAD

**Issue by EstebanC02** [Pushwoosh/pushwoosh-android-sdk#69]
Hello, thank you for the answer to the previous issue. I have a new problem trying to add the following line:

`PushwooshLocation.startLocationTracking();`

It generates a duplicate message for me to activate localization services, regardless of whether the answer is to accept or cancel.

Test performed in: Genymotion HTC One - 4.4.4 API 19

Attached images.
![screen shot 2017-09-14 at 11 57 33 am](https://user-images.githubusercontent.com/11792308/30443306-ae6c6220-9944-11e7-8daf-de9bdaa5bd2c.png)
![screen shot 2017-09-14 at 11 57 50 am](https://user-images.githubusercontent.com/11792308/30443311-b1bf214c-9944-11e7-8132-1b9f1ea185e3.png)
![screen shot 2017-09-14 at 11 57 56 am](https://user-images.githubusercontent.com/11792308/30443315-b49d90f6-9944-11e7-9a61-1299cca518e0.png)
![screen shot 2017-09-14 at 11 58 00 am](https://user-images.githubusercontent.com/11792308/30443323-b814d9a6-9944-11e7-80fa-fca2e413d61d.png)
![screen shot 2017-09-14 at 11 58 05 am](https://user-images.githubusercontent.com/11792308/30443332-baee65d4-9944-11e7-8592-dac7aa8eaf39.png)

**Comment by wfhm** [comment]
Hi,

Checking it.

**Comment by wfhm** [comment]
@EstebanC02 

Fixed in [5.1.0](https://github.com/Pushwoosh/pushwoosh-android-sdk/releases/tag/5.1.0).
