### ISSUE TITLE
Setting Android icon in JSON api - does not set notification bar icon on android 5.0

### ISSUE THREAD

**Issue by kgpmurray** [Pushwoosh/pushwoosh-android-sdk#7]
Setting Android icon in JSON api - does not set notification bar icon on android 5.0.
App still uses the app icon, which becomes a white square on android 5.0

**Comment by molhamstein** [comment]
any solution for this ?

**Comment by sudotong** [comment]
Any solutions for this?

**Comment by shaders** [comment]
Finally our team has figured out the issue.

As you know the icons has been changed on Lollipop to be white only. Therefore if you select targetSdkVersion >= 21 in your AndroidManifest.xml Android will use alpha-channel of the icon only.

See more on the behavior:
https://developer.android.com/about/versions/android-5.0-changes.html#BehaviorNotifications
The system ignores all non-alpha channels in action icons and in the main notification icon. You should assume that these icons will be alpha-only. The system draws notification icons in white and action icons in dark gray.

This is beyond Pushwoosh SDK control.
However you can revert this behavior to use old style colored icons:
1. Set targetSdkVersion to 19. This automatically brings the old behavior back.
OR
2. Create the notification icon according to the guidelines:
http://developer.android.com/design/style/iconography.html#notification
The system will ignore all the colors as per:
https://developer.android.com/about/versions/android-5.0-changes.html#BehaviorNotifications
2.1 Name the icon as pw_notification.png. Pushwoosh SDK will use this icon as default for notifications.
2.2 Alternatively you can use Remote API and set android_icon parameter to the icon image (without file extension)
