### ISSUE TITLE
Not working on Android 26 with app targeting 26. Notification channels..?

### ISSUE THREAD

**Issue by gajicm93** [Pushwoosh/pushwoosh-android-sdk#73]
SDK successfully sends getInApps and applicationOpen events, but not a "register" event, getPushToken always returns null, and notifications are not being received.

When I ran the exact same on the older device, works perfectly. Are you using the new notification channels on the API 26?

**Comment by andrijans** [comment]
I have the same problem

**Comment by wfhm** [comment]
@gajicm93 @andrijans 

Hi,

This is quite strange. Can you clarify whether you see a /registerDevice API request being sent in a device log and failing or is it not sent at all? Also could you please specify Pushwoosh SDK version in question and provide us with a full device log?

**Comment by andrijans** [comment]
So I debugged it a little bit more. When I run the code for the first time in app it calls getInApps registerUser and applicationOpen. In console I can see for example 0/1 Then I manually uninstall application, run a new build and then it sends getInApps, applicationOpen and registerDevice and than push is working and i can see in console 1/1 devices

**Comment by andrijans** [comment]
So if it's clean install it works but if its update from version that didn't have notifications than it doesn't work

**Comment by gajicm93** [comment]
Exactly, that might be the problem, in my project I first implemented FCM, then tested it separately first, and after that included Pushwoosh in the project, and by the first time I run it, FCM already had it's token set up. So this might be a bit of an edge case.

**Comment by andrijans** [comment]
I didn"t have FCM implemented before. I just opened an issue https://community.pushwoosh.com/questions/4585/pushwoosh-511-not-registering-device
so hopefully someone will answer.

**Comment by wfhm** [comment]
@gajicm93 @andrijans 

Thanks for the details! We are investigating it.

**Comment by andrijans** [comment]
@wfhm 
If I call Pushwoosh.getInstance().getPushToken() it returns null and if i call FirebaseInstanceId.getInstance().getToken() it returns the token

**Comment by wfhm** [comment]
@gajicm93 @andrijans We have found the root of the issue, a fix will be rolled out with the next release.

**Comment by andrijans** [comment]
@wfhm when will that be?

**Comment by wfhm** [comment]
@andrijans We expect it to be released in the next two weeks.

**Comment by wfhm** [comment]
@gajicm93 @andrijans fixed in 5.4.0.
