### ISSUE TITLE
(un)registerForPushNotifications sometimes not triggering callback

### ISSUE THREAD

**Issue by gajicm93** [Pushwoosh/pushwoosh-android-sdk#75]
When I call one of these 2 methods, very often the callback never gets called, even though I see in the logs that [RequestManager] successfully completed the request. No rule or pattern whatsoever, but I think it works properly only the first time after installing the app (or clearing app data), while it starts acting funny following an app restart..

**Comment by wfhm** [comment]
Hi, checking this.

**Comment by wfhm** [comment]
@gajicm93 Will be fixed with the next release.

**Comment by wfhm** [comment]
@gajicm93 fixed in 5.4.1
