### ISSUE TITLE
[RequestManager] calls "registerDevice" without me explicitly calling registerForPushNotifications, even though I unregistered previously

### ISSUE THREAD

**Issue by gajicm93** [Pushwoosh/pushwoosh-android-sdk#76]
Ok, I don't know if this is the proper practice for disabling notifications, but I call unregisterForPushNotifications, wait for success callback, and than save to SharedPreferences that notifications are disabled, and never again call registerForPushNotifications unless user explicitly tries to register for notifications again.

But I see in the logs that RequestManager (on subsequent app start) calls "registerDevice" even though I never explicitly called registerForPushNotifications, and even though I previously unregistered..

This is a serious issue, and how do I disable notifications permanently anyway?

**Comment by gajicm93** [comment]
Now I even explicitly tried calling ONLY unregister on app start (if registration status is false in SharedPrefs), and in the logs I can see "register" being called first, and then "unregister" immediately after..

**Comment by wfhm** [comment]
Hi,

Checking this. Meanwhile, could you please provide us with your device log illustrating the issue.

**Comment by wfhm** [comment]
@gajicm93 Got it reproduced. The fix will be rolled out with the next release.

**Comment by n-belokopytov** [comment]
@wfhm what kind of a fix? unregisterForPushNotifications will work and automatic registerDevice calls will be dropped if it was called?

**Comment by wfhm** [comment]
@n-belokopytov 

Exactly. `unregisterForPushNotifications()` will work and, also, `registerDevice` will not automatically be called in that case.

**Comment by wfhm** [comment]
@gajicm93 @n-belokopytov fixed in 5.4.0.
