### ISSUE TITLE
`GET_ACCOUNTS` permission no longer needed

### ISSUE THREAD

**Issue by sandstrom** [Pushwoosh/pushwoosh-android-sdk#8]
The `GET_ACCOUNTS` permission is no longer needed for GCM to work.

It used to be required for registration to GCM, but a recent Play Services update stopped using the Google account even on Froyo and Gingerbread. If you are registering to GCM with Play Services (i.e. With `GoogleCloudMessaging.register`), you no longer need this permission on any Android version.

If you are using the deprecated library (GCMRegistrar.register), you still need a Google Account on pre 4.0.4 version, which requires that permission.

So, it would be awesome if you could drop this from the SDK (entirely or for the min versions where it's possible).

Asking for permissions tend to affect downloads (lower conversion rates in Play Store). Also, Google recommends asking for no more permissions than necessary[1].

[1] https://developer.android.com/training/articles/security-tips.html#RequestingPermissions

**Comment by shaders** [comment]
That's not quite right. Let me explain. GCM technology is not a client-side library, it is a part of the Android OS.
Indeed GCM library or GoogleCloudMessaging library in terms we usually speak of is a client side code that is linked to and goes with your app.

If you take a look on the source code of GoogleCloudMessaging library you can see that it uses the same Intent as original GCM library to register for GCM: "com.google.android.c2dm.intent.REGISTER"

In other words these libraries are doing the same thing just with the different source code.
It doesn't matter which library do you use as GCM is a part of the Android OS and you will need GET_ACCOUNTS permission on lower Androids.

From Android docs:
The android.permission.GET_ACCOUNTS permission as GCM requires a Google account (necessary only if if the device is running a version lower than Android 4.0.4)

Even Google example on GoogleCloudMessaging library uses this permission:
https://code.google.com/p/gcm/source/browse/gcm-client/GcmClient/src/main/AndroidManifest.xml

I hope it clears the things up!

**Comment by sandstrom** [comment]
According to [these](http://stackoverflow.com/questions/25498608/why-google-account-login-is-required-for-gcm-to-work-for-devices-below-4-0-4-os/25498683#25498683) [two](http://stackoverflow.com/questions/18444227/get-accounts-permission-while-using-gcm-why-is-this-needed) it isn't (they allegedly quote Google developers). But that may be wrong, you are in a better position to determine that!

Regardless, it's not needed for Android above 4.0.4 so this issue mainly concerns not including the permission when the sdk min version is above 4.0.4.

To reiterate, this scares away customers for us (lower conversion rate in Google Play), also Google recommends asking for no more permissions than necessary[1].

[1] https://developer.android.com/training/articles/security-tips.html#RequestingPermissions

**Comment by shaders** [comment]
Ok, I see what is going on now :) I was not correct. Actually installation of Google Play Services (automatic) added the new component (old one was GSF and could be seen in old GCM registration code). The new code uses the following code:  
    Intent localIntent = new Intent("com.google.android.c2dm.intent.REGISTER");
    localIntent.setPackage("com.google.android.gms");

The old code used:  
    Intent localIntent = new Intent("com.google.android.c2dm.intent.REGISTER");
    localIntent.setPackage("com.google.android.gsf");

I'll keep you posted.

**Comment by sandstrom** [comment]
Great! Thanks for the quick replies too! :smiley: 

We're in the process of moving away from Urban Airship and your product seems great in most aspects! However, we're seeing that too many permissions lowers Play Store conversions/downloads, so reducing them would be beneficial.

**Comment by shaders** [comment]
The 2.9.0 Android SDK is now based on GMS and should work without GET_ACCOUNTS permission on older device (tested). Let me know how it works for you!

**Comment by sandstrom** [comment]
Great! I'll try it out, presumably it'll work just fine, but I'll let you know if it doesn't.

Thanks! :fireworks:

**Comment by sandstrom** [comment]
I'm preparing a release of our app, now that these things have been solved.

- I noted this is still in the cordova plugin (https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/blob/master/plugin.xml#L38).
- Will the cordova plugin automatically pickup the new 2.9.0 Android version, or does it need to lock it in within the Cordova plugin somehow?
- Could the `3.4.11` version of the Cordova plugin be published to the Cordova plugin registry?

**Comment by shaders** [comment]
Thank you for the feedback! 
The plugin version is 3.4.12. However plugman hangs when trying to update the cordova plugins repository. I'll try again later.

**Comment by shaders** [comment]
Plugin published  
http://plugins.cordova.io/#/search?search=pushwoosh

**Comment by sandstrom** [comment]
Great, much appreciated!
