### ISSUE TITLE
Docs: Using Pushwoosh SDK with other FCM messaging services

### ISSUE THREAD

**Issue by datrixo** [Pushwoosh/pushwoosh-android-sdk#83]
Hi.

On the FAQ: http://docs.pushwoosh.com/docs/android-faq#section-using-pushwoosh-sdk-with-other-fcm-messaging-services (which should be included in documentation by the way) You are suggesting that developer should extends PushFcmIntentService, FcmRegistrationService.

But why developer should rely on your classes when we speaking about FCM routing service (not pushwoosh routing service)? That dependency should be reversed. The FCM is a "base" service that is used by pushwoosh and others.

It can be just something like this (it works of course, but I shouldn't create your service like that):
```
class FirebaseInstanceIdRouterService : FirebaseInstanceIdService() {

    override fun onTokenRefresh() {
        super.onTokenRefresh()
        FcmRegistrationService().onTokenRefresh()
    }

}
```

Next thing (from Pushwoosh docs):
```
    private boolean isPushwooshRemoteMessage(RemoteMessage remoteMessage) {
        //fcm_sender_id here is a "Sender ID" connected to Pushwoosh application
        return getApplicationContext().getString(R.string.fcm_sender_id).equals(remoteMessage.getFrom());
    }
```

That isn't true.  This same condition will be correct when any one will try to send notification directly from FirebaseConsole. Could You provide a way to clearly recognize remote messages from Pushwoosh?

The dirty(unreliable) solution:
```
    fun isPushwooshNotification(remoteMessage: RemoteMessage): Boolean {
        return remoteMessage.data.containsKey("pw_msg")
    }
```

**Comment by wfhm** [comment]
Hi,

Thank you for your feedback!

We will review this part of Pushwoosh SDK and figure out whether it is possible to make this interface more comfortable for users with the next release.

**Comment by wfhm** [comment]
@datrixo 

We have reworked this behavior in the latest release, so now you can handle push token changes and message routing in the following way:

```
public class FirebaseMessagingRouterService extends FirebaseMessagingService {

  @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        if (PushwooshFcmHelper.isPushwooshMessage(remoteMessage)) {
           //this is a Pushwoosh push, SDK will handle it automatically
            PushwooshFcmHelper.onMessageReceived(remoteMessage)
        } else {
            //this is not a Pushwoosh push, you should handle it by yourself
            dispatchNonPushwooshMessage(remoteMessage);
        }
    }
  
    private void dispatchNonPushwooshMessage(RemoteMessage remoteMessage) {
       // Implement your push handling logics here    }
```

```

public class FirebaseInstanceIdRouterService extends FirebaseInstanceIdService {

    @Override
    public void onTokenRefresh() {
        // Get updated InstanceID token.
        val refreshedToken = FirebaseInstanceId.getInstance().token

        // Send a new token to Pushwoosh
        PushwooshFcmHelper.onTokenRefresh(refreshedToken)
        sendTokenToAnotherService(token);
    }

    private void sendTokenToAnotherService(String token) {
        // Implement your token handling logics here
    }
}

Please let us know if you have any questions or suggestions!

**Comment by Pagebakers** [comment]
How to include the PushwooshFcmHelper? I can't find this in the package.
