### ISSUE TITLE
Local notifications on app update duplicate

### ISSUE THREAD

**Issue by n-belokopytov** [Pushwoosh/pushwoosh-android-sdk#84]
Hello, judging from our metrics, on **5.4.2** the **local notifications** get duplicated when the app is updated - they are not being cleared from the Alarm Manager, when we call "clear all" before re-scheduling them. Could that be the case?

**Comment by wfhm** [comment]
Hi,

Checking it.

**Comment by n-belokopytov** [comment]
@wfhm additionally please check out whether you do not duplicate scheduled notifications on phone reboot

**Comment by n-belokopytov** [comment]
@wfhm any news? we still receive a lot of crashes because of the local notifications on releasing a new update.

**Comment by wfhm** [comment]
@n-belokopytov 

We were unable to reproduce the issue locally yet. This issue is in our pipeline, however it will most likely not be fixed with the nearest upcoming release.

**Comment by Nissshhh** [comment]
hello any update on this issue.

**Comment by wfhm** [comment]
@Nissshhh could you please describe the issue in a bit more details? Is it possible to provide us with the steps to reproduce it?

**Comment by wfhm** [comment]
@Nissshhh any updates?

**Comment by wfhm** [comment]
@Nissshhh Thank you for the feedback!
