### ISSUE TITLE
not working with gradle 3.0.1, google-services -11.0.6

### ISSUE THREAD

**Issue by ibrahimgharyali** [Pushwoosh/pushwoosh-android-sdk#88]
It was working fine with older versions, I updated the gradle  and google-services and bamm, now It is not able to sync pushwoosh files on gradle sync
FYI:- I have also updated project to  pushwoosh 5.5

**Comment by wfhm** [comment]
Hi, checking it.

**Comment by Vichy97** [comment]
I also am running into this issue. I cant use older google play services because of other things in my app

**Comment by ibrahimgharyali** [comment]
I fixed the issue by using the older version of pushwoosh 4.10.8. `compile 'com.pushwoosh:pushwoosh:4.10.8'`   If you wish to use pushwoosh 5.5, then you need to reconfigure your project according to pushwoosh and a lot of your classes will not be usable like `BasePushMessageReceiver` ,  `AbsNotificationFactory` . hope it helps

**Comment by Vichy97** [comment]
I think this issue is not really resolved. Using an outdated version of pushwoosh is just a work around to the actual problem

**Comment by wfhm** [comment]
@ibrahimgharyali @Vichy97 It works for me with gradle 3.0.1 and with google-play-services:11.0.4 using pushwoosh-android-sdk:5.5.2. May I ask you describe the issue in a bit more details? What exactly is not working?

**Comment by Vichy97** [comment]
I am seeing `java.lang.ClassNotFoundException: com.pushwoosh.plugin.pushnotifications.NotificationFactory`

**Comment by wfhm** [comment]
@Vichy97 could you please specify which framework it is related to? Also, this exception should be handled automatically by Pushwoosh SDK, so could you please specify whether it actually causes a crash or does this message just persist in device logs?

**Comment by Vichy97** [comment]
@wfhm Im not sure what framework it is related to. I see that error and it doesnt crash but then pushwoosh does receive notifications.

**Comment by wfhm** [comment]
@Vichy97 If it doesn't crash and does receive notifications, what is the issue then?

**Comment by Vichy97** [comment]
Sorry that was a typo. it doesnt receive notifications

**Comment by wfhm** [comment]
@Vichy97 

That's quite strange, we could not reproduce it on our side. May I ask you to share an .APK with us via help@pushwoosh.com so we could check it it? Please do not forget to specify this issue in your email.

**Comment by wfhm** [comment]
@Vichy97 

Could you please let us know whether you had contacted our support team? We were unable to find any requests referring to this issue yet.

**Comment by Vichy97** [comment]
@wfhm Im sorry I didnt get back to you on this. I was out of town for a while. I did end up getting it working. This issue can be closed
