### ISSUE TITLE
Action "URL" notifications not working in combination with NotificationServiceExtension

### ISSUE THREAD

**Issue by gajicm93** [Pushwoosh/pushwoosh-android-sdk#89]
I implemented my own NotificationServiceExtension to intercept "URL" notifications, and open my app before Pushwoosh opens the URL in the browser. I just overrode "onMessageOpened" and started an Activity Intent from the callback, and even though I'm properly calling super() and everything, Pushwoosh stops automatically opening browser when my app is in foreground, while it seems to sometimes work and sometimes not for the background case..

Do you have any idea what the problem might be, or any other better solution for my use case? I just need to open my app before starting browser, so when the user clicks back button in the browser, he gets taken back to my app instead of home screen.

Thanks.

**Comment by wfhm** [comment]
Hey @gajicm93,

That's quite strange. Clicking on an "URL" push notifications will still lead you to your application, to the LAUNCHER activity in particular. Could it be that you finish this activity before you can navigate to it with "Back" button?

Also, could you please specify a Pushwoosh Android SDK version used in your project?

**Comment by gajicm93** [comment]
@wfhm Got some additional info regarding the issue. It seems like the only problem is that the browser is not automatically started, but when you run it manually via icon, the proper page from the notification is opened.

As if the notification adds the URL to some browser page stack, but just doesn't run the app..

**Comment by wfhm** [comment]
@gajicm93 

May I ask you to share your APK with us so we could try it on our side? If yes, please send it over support@pushwoosh.com. Also, if you use a custom Notification Factory, could you please provide us with its code?

**Comment by wfhm** [comment]
@gajicm93 

There are 2 options to send an URL push with Pushwoosh - sending it with "Open URL" action and sending it with "Remote page" action.

"Open URL" notifications will always open an external browser, and there is no way to control this behavior. "Remote page" notifications, on the other hand, open a remote URL inside your application, therefore, if your goal is just opening URLs inside your app, it is what you are looking for.

To send a "Remote page" notification, just add `"remote_page" : "http://myremoteurl.com"` key-value pair to your /createMessage API request, or select **Remote Page** action in Send Push tab in the Control Panel:

![screen shot 2017-12-27 at 15 15 28](https://user-images.githubusercontent.com/13344781/34375392-e706705a-eb18-11e7-8231-a8db6e48213d.png)

**Comment by gajicm93** [comment]
@wfhm I'm using the standard "Open URL" method, and have successfully intercepted it with this code:

```
public class NotificationService extends NotificationServiceExtension {

    @Override
    protected void onMessageOpened(PushMessage pushMessage) {
        super.onMessageOpened(pushMessage);
        Intent appIntent = new Intent(getApplicationContext(), Activity.class);
        appIntent.setFlags(appIntent.getFlags() | Intent.FLAG_ACTIVITY_NEW_TASK);
        appIntent.putExtras(pushMessage.toBundle());
        getApplicationContext().startActivity(appIntent);
    }

}
```

The problem is that with this code, automatic URL opening sometimes stop working.. And it also depends if app is in foreground or background.. I can't see any clear pattern and seems to be acting differently on different phones..

**Comment by wfhm** [comment]
@gajicm93 

I sincerely apologize for such a delayed response! Could you please let us know whether you were able to resolve this issue, and if there is any news on it? 

Also, did you have a chance to test sending pushes with "Remote page" action?

**Comment by gajicm93** [comment]
@wfhm I didn't worked on it since then much, and didn't resolve it, only hacked around it a bit my manually opening the desired URL from my own code.. But there's a problem with that approach that when your code also happens to work, URL gets opened 2 times..

But essentially, I gave you the complete code that creates the issue, so just try reproducing it.. Test a few phones, and test both background and foreground cases..

Regarding "Remote page", I think it's not part of my package (requires more expensive package), but even if that works it's not a solution, since people who send notifications are used to this standard method of sending URL notifications..

**Comment by wfhm** [comment]
@gajicm93 I strongly apologize for such a long delay in correspondence. Is this issue still persistent in recent plugin versions?

**Comment by wfhm** [comment]
Closed until there is more info to work with.
