### ISSUE TITLE
Make `READ_PHONE_STATE` permission optional (or remove it)

### ISSUE THREAD

**Issue by sandstrom** [Pushwoosh/pushwoosh-android-sdk#9]
This permission is scaring people away. Is this something you could remove or make optional?

As far as I know it's not needed to delivering push notifications.

![ekvpe](https://cloud.githubusercontent.com/assets/122287/6023809/3248354c-abc7-11e4-9f8c-39849efbcb72.png)

**Comment by shaders** [comment]
The SDK uses this permission to get DeviceId of the device if ANDROID_ID is not available.

    final String deviceId = ((TelephonyManager) context.getSystemService(Context.TELEPHONY_SERVICE)).getDeviceId();

You can omit this permission in your APK. But if ANDROID_ID will not be available features like AppGroups or cross-application user targeting will not work for this device.

**Comment by sandstrom** [comment]
Great I'll open a request in the cordova repo to make it optional.

For a while we were considering switching to another push plugin because all permissions are suppressing our download/conversion rates. But if we can make this one optional along with skipping `GET_ACCOUNTS` for the majority, and growing, chunk of 4+ devices that don't need it, I think we'll be able to keep using it.

I appreciate that you help out here!
