### ISSUE TITLE
Throwing an IllegalStateException when packup is disallowed in manifest 

### ISSUE THREAD

**Issue by molhamstein** [Pushwoosh/pushwoosh-android-sdk#91]
I have updated recently to the pushwoosh android SDK V5.5.2
and now the app is crashing once I call

` Pushwoosh.getInstance() `

and throwing 
IllegalStateException Pushwoosh library not initialized. Please use Pushwoosh library after Application.onCreate() method

I have backUp disabled on my application tag in the manifest 

`android:allowBackup="false"`

and after wasting a long time on it 
once i removed the previous property from the manifest everything is working fine

**Comment by wfhm** [comment]
Hi,

Checking it.

**Comment by wfhm** [comment]
@molhamstein 

Please accept our sincere apologies for a delayed response! Could you please let us know whether you were able to figure out this issue?

Please note that we were unable to reproduce this issue with 5.5.3 version of Pushwoosh SDK.

**Comment by molhamstein** [comment]
actually I haven't done anything regarding this point, as i mentioned above all i did was remove the backup flag and now its working for me, I'm not sure what is the relation between the issue and this flag
