### ISSUE TITLE
Glide RequestListener not workin how to solve this problem

### ISSUE THREAD

**Issue by Prabha10cs** [Pushwoosh/pushwoosh-android-sdk#92]
Glide
                        .with(context)
                        .load(movie.getlogo())
                        .placeholder(R.drawable.ic_refreshing)
                        .priority(Priority.IMMEDIATE)
                        .crossFade()
                        .diskCacheStrategy(DiskCacheStrategy.NONE)
                        .skipMemoryCache(true)
                        .listener(new RequestListener<String, GlideDrawable>() {
                            @Override
                            public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                                System.out.println("glideee//////onLoadFailed"+movie.getlogo());
                                return false;
                            }

                            @Override
                            public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                                System.out.println("glideee//////onResourceReady"+movie.getlogo());
                                sharedPreference.putString(context,"get_loadd","okk");
                                holder.item_layout.setVisibility(View.VISIBLE);
                                holder.icon1.setVisibility(View.VISIBLE);

                                return false;
                            }
                        })
                        .into(holder.icon1);

**Comment by wfhm** [comment]
Hi,

It looks like it is not related to Pushwoosh SDK. Might it me a good idea to contact Glide team in [their repo](https://github.com/bumptech/glide)?
