### ISSUE TITLE
[PushwooshLocation] Question: when is the stopLocationTracking() should be called?

### ISSUE THREAD

**Issue by dmytroKarataiev** [Pushwoosh/pushwoosh-android-sdk#94]
The docs don't have a lot of information, so I have a question about the Locations API:
When do you need to call the stopLocationTracking() method? Is it supposed to stop your tracking forever, so you don't really need to call this method on each app exit?

**Comment by wfhm** [comment]
Hi,

This method indeed stops location tracking until the moment you call `startLocationTracking()` once again. If you do not automatically start location tracking on every application launch, you do not need to call it on each app exit.
