### ISSUE TITLE
Can Pushwoosh work with Gradle 2.3

### ISSUE THREAD

**Issue by strider1981** [Pushwoosh/pushwoosh-android-sdk#96]
Is there any work around to get the SDK working with gradle 2.3.2? When I upgrade my project to gradle 3.0 and integrate the SDK I get an multidex merge error.

**Comment by wfhm** [comment]
Hi, 

You can try using an older SDK version, that does not require newer Gradle versions. @5.4.1 should work for you.

Meanwhile, could you please provide us with the multidex error log?

**Comment by strider1981** [comment]
Hi, I got it fixed. Issue was with some other SDK I was using. It works fine now. Thanks
